### ISSUE TITLE
FATAL:AttributeError: 'NoneType' object has no attribute 'payload_as_int'

### ISSUE THREAD

**Issue by alexpiet** [AllenNeuralDynamics/dynamic-foraging-task#1061]
This issue was automatically generated from GUI logs.<br><br>file: Foraging.py<br>function: exception_hook<br>line 4769<br>logfile: W10DT714670/W10DT714670-A_gui_log_2024-11-22_10-12-49.txt<br>boxes: ephys4<br>count: 2<br>text: FATAL:AttributeError: 'NoneType' object has no attribute 'payload_as_int'<br><details><summary> GUI Log snippet (click for full log)

```
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\svc_aind_ephys\AppData\Local\miniconda3\envs\Foraging\Lib\site-packages\StageWidget\views\widget\main_view.py", line 37, in __init__
    self.stage_model = StageModel(config)
                       ^^^^^^^^^^^^^^^^^^
  File "C:\Users\svc_aind_ephys\AppData\Local\miniconda3\envs\Foraging\Lib\site-packages\StageWidget\models\stage_model.py", line 28, in __init__
    self.device = StepperMotorDevice(config=config)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\svc_aind_ephys\AppData\Local\miniconda3\envs\Foraging\Lib\site-packages\StageWidget\models\stepper_motor_device.py", line 55, in __init__
    raise e
  File "C:\Users\svc_aind_ephys\AppData\Local\miniconda3\envs\Foraging\Lib\site-packages\StageWidget\models\stepper_motor_device.py", line 45, in __init__
    super().__init__(com_port, dump_file_path + dump_file)
  File "C:\Users\svc_aind_ephys\AppData\Local\miniconda3\envs\Foraging\Lib\site-packages\pyharp\device.py", line 49, in __init__
    self.load()
  File "C:\Users\svc_aind_ephys\AppData\Local\miniconda3\envs\Foraging\Lib\site-packages\pyharp\device.py", line 52, in load
    self.WHO_AM_I = self.read_who_am_i()
                    ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\svc_aind_ephys\AppData\Local\miniconda3\envs\Foraging\Lib\site-packages\pyharp\device.py", line 97, in read_who_am_i
    return reply.payload_as_int()
           ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'payload_as_int'
```
</summary>
Full GUI log 

```
10:12:49 AM:INFO:Foraging:Foraging.py:start_gui_log_file:line 4661:Starting logfile!
10:12:49 AM:INFO:Foraging:Foraging.py:log_git_hash:line 4672:Python version: 3.11.9 | packaged by conda-forge | (main, Apr 19 2024, 18:27:10) [MSC v.1938 64 bit (AMD64)]
10:12:49 AM:INFO:Foraging:Foraging.py:log_git_hash:line 4689:Current git commit branch, hash: main, 1a7c9d3d1aa10284caed44ba9b223c6bfbb8ff5f
10:12:49 AM:INFO:Foraging:Foraging.py:log_git_hash:line 4693:Current foraging_gui version: 1.6.10
10:12:49 AM:WARNING:Foraging:Foraging.py:log_git_hash:line 4703:local repository is clean
10:12:49 AM:INFO:Foraging:Foraging.py:<module>:line 4804:Setting QApplication attributes
10:12:49 AM:INFO:Foraging:Foraging.py:<module>:line 4812:Starting QApplication and Window
10:12:49 AM:INFO:Foraging:Foraging.py:__init__:line 69:Creating Window
10:12:49 AM:INFO:Foraging:Foraging.py:_GetSettings:line 1174:Loaded settings_box file
10:12:49 AM:INFO:Foraging:Foraging.py:_GetSettings:line 1202:Loaded settings file
10:12:49 AM:WARNING:Foraging:Foraging.py:_GetSettings:line 1212:Missing setting (FIP_workflow_path), using default: 
10:12:49 AM:WARNING:Foraging:Foraging.py:_GetSettings:line 1212:Missing setting (FIP_settings), using default: C:\Users\svc_aind_ephys\Documents\FIPSettings
10:12:49 AM:WARNING:Foraging:Foraging.py:_GetSettings:line 1212:Missing setting (bonsai_config_path), using default: C:\Users\svc_aind_ephys\Documents\GitHub\dynamic-foraging-task\bonsai\Bonsai.config
10:12:49 AM:WARNING:Foraging:Foraging.py:_GetSettings:line 1212:Missing setting (metadata_dialog_folder), using default: C:\Users\svc_aind_ephys\Documents\ForagingSettings\metadata_dialog\
10:12:49 AM:WARNING:Foraging:Foraging.py:_GetSettings:line 1212:Missing setting (rig_metadata_folder), using default: C:\Users\svc_aind_ephys\Documents\ForagingSettings\rig_metadata\
10:12:49 AM:WARNING:Foraging:Foraging.py:_GetSettings:line 1212:Missing setting (project_info_file), using default: C:\Users\svc_aind_ephys\Documents\ForagingSettings\Project Name and Funding Source v2.csv
10:12:49 AM:WARNING:Foraging:Foraging.py:_GetSettings:line 1212:Missing setting (schedule_path), using default: Z:\dynamic_foraging\DynamicForagingSchedule.csv
10:12:49 AM:WARNING:Foraging:Foraging.py:_GetSettings:line 1212:Missing setting (go_cue_decibel_box2), using default: 60
10:12:49 AM:WARNING:Foraging:Foraging.py:_GetSettings:line 1212:Missing setting (go_cue_decibel_box3), using default: 60
10:12:49 AM:WARNING:Foraging:Foraging.py:_GetSettings:line 1212:Missing setting (go_cue_decibel_box4), using default: 60
10:12:49 AM:WARNING:Foraging:Foraging.py:_GetSettings:line 1212:Missing setting (lick_spout_distance_box1), using default: 5000
10:12:49 AM:WARNING:Foraging:Foraging.py:_GetSettings:line 1212:Missing setting (lick_spout_distance_box2), using default: 5000
10:12:49 AM:WARNING:Foraging:Foraging.py:_GetSettings:line 1212:Missing setting (lick_spout_distance_box3), using default: 5000
10:12:49 AM:WARNING:Foraging:Foraging.py:_GetSettings:line 1212:Missing setting (lick_spout_distance_box4), using default: 5000
10:12:49 AM:WARNING:Foraging:Foraging.py:_GetSettings:line 1212:Missing setting (name_mapper_file), using default: C:\Users\svc_aind_ephys\Documents\ForagingSettings\name_mapper.json
10:12:49 AM:WARNING:Foraging:Foraging.py:_GetSettings:line 1212:Missing setting (save_each_trial), using default: True
10:12:49 AM:WARNING:Foraging:Foraging.py:_GetSettings:line 1212:Missing setting (manifest_flag_dir), using default: C:\Users\svc_aind_ephys\Documents\aind_watchdog_service\manifest
10:12:49 AM:WARNING:Foraging:Foraging.py:_GetSettings:line 1212:Missing setting (auto_engage), using default: True
10:12:49 AM:WARNING:Foraging:Foraging.py:_GetSettings:line 1212:Missing setting (clear_figure_after_save), using default: True
10:12:49 AM:WARNING:Foraging:Foraging.py:_GetSettings:line 1212:Missing setting (add_default_project_name), using default: True
10:12:49 AM:INFO:Foraging:Foraging.py:_LoadSchedule:line 1100:Loaded behavior schedule
10:12:49 AM:INFO:Foraging:Foraging.py:_GetWaterCalibration:line 1064:Loaded Water Calibration
10:12:49 AM:INFO:Foraging:Foraging.py:_LoadRigJson:line 1544:Skipping rig metadata creation because create_rig_metadata=False
10:12:49 AM:INFO:Foraging:Foraging.py:_LoadUI:line 275:Using ForagingGUI.ui interface
10:12:49 AM:INFO:Foraging:Foraging.py:__init__:line 119:Setting Window title: 322_EPHYS4
10:12:49 AM:INFO:Foraging:Foraging.py:_InitializeBonsai:line 1371:Trying to connect to already running Bonsai
10:12:49 AM:INFO:Foraging:Foraging.py:_ConnectOSC:line 1418:connecting to GUI and Bonsai through OSC
10:12:50 AM:INFO:Foraging:Foraging.py:_InitializeBonsai:line 1375:Could not connect: timed out
10:12:50 AM:INFO:Foraging:Foraging.py:_InitializeBonsai:line 1384:Starting Bonsai
10:12:50 AM:INFO:Foraging:Foraging.py:log_subprocess_output:line 4776:BONSAI logging starting
10:12:51 AM:INFO:Foraging:Foraging.py:_ConnectOSC:line 1418:connecting to GUI and Bonsai through OSC
10:12:52 AM:INFO:Foraging:Foraging.py:_InitializeBonsai:line 1398:Could not connect, total waiting time 0.5 seconds: timed out
10:12:52 AM:INFO:Foraging:Foraging.py:_ConnectOSC:line 1418:connecting to GUI and Bonsai through OSC
10:12:53 AM:INFO:Foraging:Foraging.py:_InitializeBonsai:line 1401:Connected to Bonsai after 1.0 seconds
10:12:53 AM:INFO:Foraging:Foraging.py:_InitializeBonsai:line 1402:Bonsai started successfully
10:12:53 AM:INFO:Foraging:Foraging.py:_ConnectSlims:line 1281:Attempting to connect to Slims
10:12:53 AM:INFO:Foraging:Foraging.py:_ConnectSlims:line 1298:Successfully connected to Slims
10:12:53 AM:WARNING:Dialogs:Dialogs.py:_LoadCalibrationParameters:line 480:could not find water calibration parameters: C:\Users\svc_aind_ephys\Documents\ForagingSettings\WaterCalibrationPar_1.json
10:12:54 AM:INFO:Foraging:Foraging.py:keyPressEvent:line 1863:processing parameter changes
10:12:54 AM:INFO:Foraging:Foraging.py:_InitializeMotorStage:line 875:Scanning for newscale stages
10:12:54 AM:INFO:Foraging:Foraging.py:_InitializeMotorStage:line 885:Could not find any instances of NewScale Stage
10:12:54 AM:INFO:Foraging:Foraging.py:_insert_stage_widget:line 255:Inserting Stage Widget
10:12:54 AM:INFO:connection:connection.py:_connect:line 688:Connecting to aibspi(10.128.108.106):2181, use_ssl: False
10:12:54 AM:INFO:client:client.py:_session_callback:line 561:Zookeeper connection established, state: CONNECTED
10:12:54 AM:INFO:connection:connection.py:_connect_attempt:line 655:Closing connection to aibspi:2181
10:12:54 AM:INFO:client:client.py:_session_callback:line 567:Zookeeper session closed, state: CLOSED
10:12:56 AM:ERROR:Foraging:Foraging.py:exception_hook:line 4769:FATAL ERROR: 
Traceback (most recent call last):
  File "C:\Users\svc_aind_ephys\Documents\GitHub\dynamic-foraging-task\src\foraging_gui\Foraging.py", line 4819, in <module>
    win = Window(box_number=box_number,start_bonsai_ide=start_bonsai_ide)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\svc_aind_ephys\Documents\GitHub\dynamic-foraging-task\src\foraging_gui\Foraging.py", line 194, in __init__
    self._load_stage()
  File "C:\Users\svc_aind_ephys\Documents\GitHub\dynamic-foraging-task\src\foraging_gui\Foraging.py", line 245, in _load_stage
    self._insert_stage_widget(widget_to_replace)
  File "C:\Users\svc_aind_ephys\Documents\GitHub\dynamic-foraging-task\src\foraging_gui\Foraging.py", line 266, in _insert_stage_widget
    self.stage_widget = get_stage_widget()
                        ^^^^^^^^^^^^^^^^^^
  File "C:\Users\svc_aind_ephys\AppData\Local\miniconda3\envs\Foraging\Lib\site-packages\StageWidget\main.py", line 22, in get_stage_widget
    return MainViewWidget(config)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\svc_aind_ephys\AppData\Local\miniconda3\envs\Foraging\Lib\site-packages\StageWidget\views\widget\main_view.py", line 37, in __init__
    self.stage_model = StageModel(config)
                       ^^^^^^^^^^^^^^^^^^
  File "C:\Users\svc_aind_ephys\AppData\Local\miniconda3\envs\Foraging\Lib\site-packages\StageWidget\models\stage_model.py", line 28, in __init__
    self.device = StepperMotorDevice(config=config)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\svc_aind_ephys\AppData\Local\miniconda3\envs\Foraging\Lib\site-packages\StageWidget\models\stepper_motor_device.py", line 55, in __init__
    raise e
  File "C:\Users\svc_aind_ephys\AppData\Local\miniconda3\envs\Foraging\Lib\site-packages\StageWidget\models\stepper_motor_device.py", line 45, in __init__
    super().__init__(com_port, dump_file_path + dump_file)
  File "C:\Users\svc_aind_ephys\AppData\Local\miniconda3\envs\Foraging\Lib\site-packages\pyharp\device.py", line 49, in __init__
    self.load()
  File "C:\Users\svc_aind_ephys\AppData\Local\miniconda3\envs\Foraging\Lib\site-packages\pyharp\device.py", line 52, in load
    self.WHO_AM_I = self.read_who_am_i()
                    ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\svc_aind_ephys\AppData\Local\miniconda3\envs\Foraging\Lib\site-packages\pyharp\device.py", line 97, in read_who_am_i
    return reply.payload_as_int()
           ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'payload_as_int'
```
</details>

**Comment by alexpiet** [comment]
This issue reoccurred:<br><br>file: Foraging.py<br>function: exception_hook<br>line 4769<br>logfile: W10DT714670/W10DT714670-A_gui_log_2024-12-09_09-03-58.txt<br>boxes: ephys4<br>count: 9<br>text: FATAL:AttributeError: 'NoneType' object has no attribute 'payload_as_int'<br><details><summary> GUI Log snippet (click for full log)

```
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\svc_aind_ephys\AppData\Local\miniconda3\envs\Foraging\Lib\site-packages\StageWidget\views\widget\main_view.py", line 37, in __init__
    self.stage_model = StageModel(config)
                       ^^^^^^^^^^^^^^^^^^
  File "C:\Users\svc_aind_ephys\AppData\Local\miniconda3\envs\Foraging\Lib\site-packages\StageWidget\models\stage_model.py", line 28, in __init__
    self.device = StepperMotorDevice(config=config)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\svc_aind_ephys\AppData\Local\miniconda3\envs\Foraging\Lib\site-packages\StageWidget\models\stepper_motor_device.py", line 55, in __init__
    raise e
  File "C:\Users\svc_aind_ephys\AppData\Local\miniconda3\envs\Foraging\Lib\site-packages\StageWidget\models\stepper_motor_device.py", line 45, in __init__
    super().__init__(com_port, dump_file_path + dump_file)
  File "C:\Users\svc_aind_ephys\AppData\Local\miniconda3\envs\Foraging\Lib\site-packages\pyharp\device.py", line 49, in __init__
    self.load()
  File "C:\Users\svc_aind_ephys\AppData\Local\miniconda3\envs\Foraging\Lib\site-packages\pyharp\device.py", line 52, in load
    self.WHO_AM_I = self.read_who_am_i()
                    ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\svc_aind_ephys\AppData\Local\miniconda3\envs\Foraging\Lib\site-packages\pyharp\device.py", line 97, in read_who_am_i
    return reply.payload_as_int()
           ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'payload_as_int'
```
</summary>
Full GUI log 

```
09:03:58 AM:INFO:Foraging:Foraging.py:start_gui_log_file:line 4661:Starting logfile!
09:03:58 AM:INFO:Foraging:Foraging.py:log_git_hash:line 4672:Python version: 3.11.9 | packaged by conda-forge | (main, Apr 19 2024, 18:27:10) [MSC v.1938 64 bit (AMD64)]
09:03:58 AM:INFO:Foraging:Foraging.py:log_git_hash:line 4689:Current git commit branch, hash: main, 1a7c9d3d1aa10284caed44ba9b223c6bfbb8ff5f
09:03:58 AM:INFO:Foraging:Foraging.py:log_git_hash:line 4693:Current foraging_gui version: 1.6.10
09:03:58 AM:WARNING:Foraging:Foraging.py:log_git_hash:line 4703:local repository is clean
09:03:58 AM:INFO:Foraging:Foraging.py:<module>:line 4804:Setting QApplication attributes
09:03:58 AM:INFO:Foraging:Foraging.py:<module>:line 4812:Starting QApplication and Window
09:03:58 AM:INFO:Foraging:Foraging.py:__init__:line 69:Creating Window
09:03:58 AM:INFO:Foraging:Foraging.py:_GetSettings:line 1174:Loaded settings_box file
09:03:58 AM:INFO:Foraging:Foraging.py:_GetSettings:line 1202:Loaded settings file
09:03:58 AM:WARNING:Foraging:Foraging.py:_GetSettings:line 1212:Missing setting (FIP_workflow_path), using default: 
09:03:58 AM:WARNING:Foraging:Foraging.py:_GetSettings:line 1212:Missing setting (FIP_settings), using default: C:\Users\svc_aind_ephys\Documents\FIPSettings
09:03:58 AM:WARNING:Foraging:Foraging.py:_GetSettings:line 1212:Missing setting (bonsai_config_path), using default: C:\Users\svc_aind_ephys\Documents\GitHub\dynamic-foraging-task\bonsai\Bonsai.config
09:03:58 AM:WARNING:Foraging:Foraging.py:_GetSettings:line 1212:Missing setting (metadata_dialog_folder), using default: C:\Users\svc_aind_ephys\Documents\ForagingSettings\metadata_dialog\
09:03:58 AM:WARNING:Foraging:Foraging.py:_GetSettings:line 1212:Missing setting (rig_metadata_folder), using default: C:\Users\svc_aind_ephys\Documents\ForagingSettings\rig_metadata\
09:03:58 AM:WARNING:Foraging:Foraging.py:_GetSettings:line 1212:Missing setting (project_info_file), using default: C:\Users\svc_aind_ephys\Documents\ForagingSettings\Project Name and Funding Source v2.csv
09:03:58 AM:WARNING:Foraging:Foraging.py:_GetSettings:line 1212:Missing setting (schedule_path), using default: Z:\dynamic_foraging\DynamicForagingSchedule.csv
09:03:58 AM:WARNING:Foraging:Foraging.py:_GetSettings:line 1212:Missing setting (go_cue_decibel_box2), using default: 60
09:03:58 AM:WARNING:Foraging:Foraging.py:_GetSettings:line 1212:Missing setting (go_cue_decibel_box3), using default: 60
09:03:58 AM:WARNING:Foraging:Foraging.py:_GetSettings:line 1212:Missing setting (go_cue_decibel_box4), using default: 60
09:03:58 AM:WARNING:Foraging:Foraging.py:_GetSettings:line 1212:Missing setting (lick_spout_distance_box1), using default: 5000
09:03:58 AM:WARNING:Foraging:Foraging.py:_GetSettings:line 1212:Missing setting (lick_spout_distance_box2), using default: 5000
09:03:58 AM:WARNING:Foraging:Foraging.py:_GetSettings:line 1212:Missing setting (lick_spout_distance_box3), using default: 5000
09:03:58 AM:WARNING:Foraging:Foraging.py:_GetSettings:line 1212:Missing setting (lick_spout_distance_box4), using default: 5000
09:03:58 AM:WARNING:Foraging:Foraging.py:_GetSettings:line 1212:Missing setting (name_mapper_file), using default: C:\Users\svc_aind_ephys\Documents\ForagingSettings\name_mapper.json
09:03:58 AM:WARNING:Foraging:Foraging.py:_GetSettings:line 1212:Missing setting (save_each_trial), using default: True
09:03:58 AM:WARNING:Foraging:Foraging.py:_GetSettings:line 1212:Missing setting (manifest_flag_dir), using default: C:\Users\svc_aind_ephys\Documents\aind_watchdog_service\manifest
09:03:58 AM:WARNING:Foraging:Foraging.py:_GetSettings:line 1212:Missing setting (auto_engage), using default: True
09:03:58 AM:WARNING:Foraging:Foraging.py:_GetSettings:line 1212:Missing setting (clear_figure_after_save), using default: True
09:03:58 AM:WARNING:Foraging:Foraging.py:_GetSettings:line 1212:Missing setting (add_default_project_name), using default: True
09:03:58 AM:INFO:Foraging:Foraging.py:_LoadSchedule:line 1100:Loaded behavior schedule
09:03:58 AM:INFO:Foraging:Foraging.py:_GetWaterCalibration:line 1064:Loaded Water Calibration
09:03:58 AM:INFO:Foraging:Foraging.py:_LoadRigJson:line 1544:Skipping rig metadata creation because create_rig_metadata=False
09:03:58 AM:INFO:Foraging:Foraging.py:_LoadUI:line 275:Using ForagingGUI.ui interface
09:03:58 AM:INFO:Foraging:Foraging.py:__init__:line 119:Setting Window title: 322_EPHYS4
09:03:58 AM:INFO:Foraging:Foraging.py:_InitializeBonsai:line 1371:Trying to connect to already running Bonsai
09:03:58 AM:INFO:Foraging:Foraging.py:_ConnectOSC:line 1418:connecting to GUI and Bonsai through OSC
09:03:59 AM:INFO:Foraging:Foraging.py:_InitializeBonsai:line 1375:Could not connect: timed out
09:03:59 AM:INFO:Foraging:Foraging.py:_InitializeBonsai:line 1384:Starting Bonsai
09:03:59 AM:INFO:Foraging:Foraging.py:log_subprocess_output:line 4776:BONSAI logging starting
09:04:00 AM:INFO:Foraging:Foraging.py:_ConnectOSC:line 1418:connecting to GUI and Bonsai through OSC
09:04:01 AM:INFO:Foraging:Foraging.py:_InitializeBonsai:line 1398:Could not connect, total waiting time 0.5 seconds: timed out
09:04:01 AM:INFO:Foraging:Foraging.py:_ConnectOSC:line 1418:connecting to GUI and Bonsai through OSC
09:04:02 AM:INFO:Foraging:Foraging.py:_InitializeBonsai:line 1398:Could not connect, total waiting time 1.0 seconds: timed out
09:04:03 AM:INFO:Foraging:Foraging.py:_ConnectOSC:line 1418:connecting to GUI and Bonsai through OSC
09:04:03 AM:INFO:Foraging:Foraging.py:_InitializeBonsai:line 1401:Connected to Bonsai after 1.5 seconds
09:04:03 AM:INFO:Foraging:Foraging.py:_InitializeBonsai:line 1402:Bonsai started successfully
09:04:03 AM:INFO:Foraging:Foraging.py:_ConnectSlims:line 1281:Attempting to connect to Slims
09:04:03 AM:INFO:Foraging:Foraging.py:_ConnectSlims:line 1298:Successfully connected to Slims
09:04:03 AM:WARNING:Dialogs:Dialogs.py:_LoadCalibrationParameters:line 480:could not find water calibration parameters: C:\Users\svc_aind_ephys\Documents\ForagingSettings\WaterCalibrationPar_1.json
09:04:04 AM:INFO:Foraging:Foraging.py:keyPressEvent:line 1863:processing parameter changes
09:04:04 AM:INFO:Foraging:Foraging.py:_InitializeMotorStage:line 875:Scanning for newscale stages
09:04:04 AM:INFO:Foraging:Foraging.py:_InitializeMotorStage:line 885:Could not find any instances of NewScale Stage
09:04:04 AM:INFO:Foraging:Foraging.py:_insert_stage_widget:line 255:Inserting Stage Widget
09:04:04 AM:INFO:connection:connection.py:_connect:line 688:Connecting to aibspi(10.128.108.106):2181, use_ssl: False
09:04:04 AM:INFO:client:client.py:_session_callback:line 561:Zookeeper connection established, state: CONNECTED
09:04:04 AM:INFO:connection:connection.py:_connect_attempt:line 655:Closing connection to aibspi:2181
09:04:04 AM:INFO:client:client.py:_session_callback:line 567:Zookeeper session closed, state: CLOSED
09:04:06 AM:ERROR:Foraging:Foraging.py:exception_hook:line 4769:FATAL ERROR: 
Traceback (most recent call last):
  File "C:\Users\svc_aind_ephys\Documents\GitHub\dynamic-foraging-task\src\foraging_gui\Foraging.py", line 4819, in <module>
    win = Window(box_number=box_number,start_bonsai_ide=start_bonsai_ide)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\svc_aind_ephys\Documents\GitHub\dynamic-foraging-task\src\foraging_gui\Foraging.py", line 194, in __init__
    self._load_stage()
  File "C:\Users\svc_aind_ephys\Documents\GitHub\dynamic-foraging-task\src\foraging_gui\Foraging.py", line 245, in _load_stage
    self._insert_stage_widget(widget_to_replace)
  File "C:\Users\svc_aind_ephys\Documents\GitHub\dynamic-foraging-task\src\foraging_gui\Foraging.py", line 266, in _insert_stage_widget
    self.stage_widget = get_stage_widget()
                        ^^^^^^^^^^^^^^^^^^
  File "C:\Users\svc_aind_ephys\AppData\Local\miniconda3\envs\Foraging\Lib\site-packages\StageWidget\main.py", line 22, in get_stage_widget
    return MainViewWidget(config)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\svc_aind_ephys\AppData\Local\miniconda3\envs\Foraging\Lib\site-packages\StageWidget\views\widget\main_view.py", line 37, in __init__
    self.stage_model = StageModel(config)
                       ^^^^^^^^^^^^^^^^^^
  File "C:\Users\svc_aind_ephys\AppData\Local\miniconda3\envs\Foraging\Lib\site-packages\StageWidget\models\stage_model.py", line 28, in __init__
    self.device = StepperMotorDevice(config=config)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\svc_aind_ephys\AppData\Local\miniconda3\envs\Foraging\Lib\site-packages\StageWidget\models\stepper_motor_device.py", line 55, in __init__
    raise e
  File "C:\Users\svc_aind_ephys\AppData\Local\miniconda3\envs\Foraging\Lib\site-packages\StageWidget\models\stepper_motor_device.py", line 45, in __init__
    super().__init__(com_port, dump_file_path + dump_file)
  File "C:\Users\svc_aind_ephys\AppData\Local\miniconda3\envs\Foraging\Lib\site-packages\pyharp\device.py", line 49, in __init__
    self.load()
  File "C:\Users\svc_aind_ephys\AppData\Local\miniconda3\envs\Foraging\Lib\site-packages\pyharp\device.py", line 52, in load
    self.WHO_AM_I = self.read_who_am_i()
                    ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\svc_aind_ephys\AppData\Local\miniconda3\envs\Foraging\Lib\site-packages\pyharp\device.py", line 97, in read_who_am_i
    return reply.payload_as_int()
           ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'payload_as_int'
```
</details>

**Comment by ellahiltonvano** [comment]
@KanghoonJ this has only happened on EPHYS4

**Comment by KanghoonJ** [comment]
@alexpiet @nathan-mars Any suggestions about this issue?

**Comment by nathan-mars** [comment]
We've confirmed the stage controller was plugged in and powered on? I talked Ella through a similar error earlier this week and that was the issue. You should see a change in Device Manager if the stage controller is unplugged and replugged (a COM port will disappear, then reappear).

**Comment by ellahiltonvano** [comment]
@nathan-mars this is actually probably from that day. I'll close the issue and reopen if it happens again and power is on
