### ISSUE TITLE
FATAL:Exception: Settings box file does not have a newline at the end

### ISSUE THREAD

**Issue by alexpiet** [AllenNeuralDynamics/dynamic-foraging-task#1237]
This issue was automatically generated from GUI logs.<br><br>file: Foraging.py<br>function: exception_hook<br>line 4904<br>logfile: W10DT714033/W10DT714033-B_gui_log_2024-12-21_20-09-12.txt<br>boxes: 1B<br>count: 1<br>text: FATAL:Exception: Settings box file does not have a newline at the end<br><details><summary> GUI Log snippet (click for full log)

```
08:09:12 PM:INFO:Foraging:Foraging.py:start_gui_log_file:line 4796:Starting logfile!
08:09:12 PM:INFO:Foraging:Foraging.py:log_git_hash:line 4807:Python version: 3.11.9 | packaged by Anaconda, Inc. | (main, Apr 19 2024, 16:40:41) [MSC v.1916 64 bit (AMD64)]
08:09:12 PM:INFO:Foraging:Foraging.py:log_git_hash:line 4824:Current git commit branch, hash: main, 698fb9fecded812fcf96d570658d9bc3766b14c6
08:09:12 PM:INFO:Foraging:Foraging.py:log_git_hash:line 4828:Current foraging_gui version: 1.6.19
08:09:12 PM:WARNING:Foraging:Foraging.py:log_git_hash:line 4838:local repository is clean
08:09:12 PM:INFO:Foraging:Foraging.py:<module>:line 4944:Setting QApplication attributes
08:09:12 PM:INFO:Foraging:Foraging.py:<module>:line 4952:Starting QApplication and Window
08:09:12 PM:INFO:Foraging:Foraging.py:__init__:line 77:Creating Window
08:09:12 PM:INFO:Foraging:Foraging.py:_GetSettings:line 1211:Loaded settings_box file
08:09:12 PM:ERROR:Foraging:Foraging.py:_GetSettings:line 1219:Settings box file does not have a newline at the end
08:09:12 PM:ERROR:Foraging:Foraging.py:exception_hook:line 4904:FATAL ERROR: 
Traceback (most recent call last):
  File "C:\Users\svc_aind_behavior\Documents\GitHub\dynamic-foraging-task\src\foraging_gui\Foraging.py", line 4959, in <module>
    win = Window(box_number=box_number,start_bonsai_ide=start_bonsai_ide)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\svc_aind_behavior\Documents\GitHub\dynamic-foraging-task\src\foraging_gui\Foraging.py", line 99, in __init__
    self._GetSettings()
  File "C:\Users\svc_aind_behavior\Documents\GitHub\dynamic-foraging-task\src\foraging_gui\Foraging.py", line 1220, in _GetSettings
    raise Exception('Settings box file does not have a newline at the end')
Exception: Settings box file does not have a newline at the end
```
</summary>
Full GUI log 

```
08:09:12 PM:INFO:Foraging:Foraging.py:start_gui_log_file:line 4796:Starting logfile!
08:09:12 PM:INFO:Foraging:Foraging.py:log_git_hash:line 4807:Python version: 3.11.9 | packaged by Anaconda, Inc. | (main, Apr 19 2024, 16:40:41) [MSC v.1916 64 bit (AMD64)]
08:09:12 PM:INFO:Foraging:Foraging.py:log_git_hash:line 4824:Current git commit branch, hash: main, 698fb9fecded812fcf96d570658d9bc3766b14c6
08:09:12 PM:INFO:Foraging:Foraging.py:log_git_hash:line 4828:Current foraging_gui version: 1.6.19
08:09:12 PM:WARNING:Foraging:Foraging.py:log_git_hash:line 4838:local repository is clean
08:09:12 PM:INFO:Foraging:Foraging.py:<module>:line 4944:Setting QApplication attributes
08:09:12 PM:INFO:Foraging:Foraging.py:<module>:line 4952:Starting QApplication and Window
08:09:12 PM:INFO:Foraging:Foraging.py:__init__:line 77:Creating Window
08:09:12 PM:INFO:Foraging:Foraging.py:_GetSettings:line 1211:Loaded settings_box file
08:09:12 PM:ERROR:Foraging:Foraging.py:_GetSettings:line 1219:Settings box file does not have a newline at the end
08:09:12 PM:ERROR:Foraging:Foraging.py:exception_hook:line 4904:FATAL ERROR: 
Traceback (most recent call last):
  File "C:\Users\svc_aind_behavior\Documents\GitHub\dynamic-foraging-task\src\foraging_gui\Foraging.py", line 4959, in <module>
    win = Window(box_number=box_number,start_bonsai_ide=start_bonsai_ide)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\svc_aind_behavior\Documents\GitHub\dynamic-foraging-task\src\foraging_gui\Foraging.py", line 99, in __init__
    self._GetSettings()
  File "C:\Users\svc_aind_behavior\Documents\GitHub\dynamic-foraging-task\src\foraging_gui\Foraging.py", line 1220, in _GetSettings
    raise Exception('Settings box file does not have a newline at the end')
Exception: Settings box file does not have a newline at the end
```
</details>

**Comment by ellahiltonvano** [comment]
@micahwoodard @alexpiet any ideas who would have edited the settings file?

@bwtan-allen @XX-Yin it looks like this issue happened on Sat, was it one of you?

**Comment by alexpiet** [comment]
This issue reoccurred:<br><br>file: Foraging.py<br>function: exception_hook<br>line 4904<br>logfile: W10DT714672/W10DT714672-B_gui_log_2025-01-02_12-03-15.txt<br>boxes: 6B<br>count: 6<br>text: FATAL:Exception: Settings box file does not have a newline at the end<br><details><summary> GUI Log snippet (click for full log)

```
12:03:15 PM:INFO:Foraging:Foraging.py:start_gui_log_file:line 4796:Starting logfile!
12:03:16 PM:INFO:Foraging:Foraging.py:log_git_hash:line 4807:Python version: 3.11.9 | packaged by Anaconda, Inc. | (main, Apr 19 2024, 16:40:41) [MSC v.1916 64 bit (AMD64)]
12:03:16 PM:INFO:Foraging:Foraging.py:log_git_hash:line 4824:Current git commit branch, hash: main, 698fb9fecded812fcf96d570658d9bc3766b14c6
12:03:16 PM:INFO:Foraging:Foraging.py:log_git_hash:line 4828:Current foraging_gui version: 1.6.19
12:03:16 PM:WARNING:Foraging:Foraging.py:log_git_hash:line 4838:local repository is clean
12:03:16 PM:INFO:Foraging:Foraging.py:<module>:line 4944:Setting QApplication attributes
12:03:16 PM:INFO:Foraging:Foraging.py:<module>:line 4952:Starting QApplication and Window
12:03:16 PM:INFO:Foraging:Foraging.py:__init__:line 77:Creating Window
12:03:16 PM:INFO:Foraging:Foraging.py:_GetSettings:line 1211:Loaded settings_box file
12:03:16 PM:ERROR:Foraging:Foraging.py:_GetSettings:line 1219:Settings box file does not have a newline at the end
12:03:16 PM:ERROR:Foraging:Foraging.py:exception_hook:line 4904:FATAL ERROR: 
Traceback (most recent call last):
  File "C:\Users\svc_aind_behavior\Documents\GitHub\dynamic-foraging-task\src\foraging_gui\Foraging.py", line 4959, in <module>
    win = Window(box_number=box_number,start_bonsai_ide=start_bonsai_ide)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\svc_aind_behavior\Documents\GitHub\dynamic-foraging-task\src\foraging_gui\Foraging.py", line 99, in __init__
    self._GetSettings()
  File "C:\Users\svc_aind_behavior\Documents\GitHub\dynamic-foraging-task\src\foraging_gui\Foraging.py", line 1220, in _GetSettings
    raise Exception('Settings box file does not have a newline at the end')
Exception: Settings box file does not have a newline at the end
```
</summary>
Full GUI log 

```
12:03:15 PM:INFO:Foraging:Foraging.py:start_gui_log_file:line 4796:Starting logfile!
12:03:16 PM:INFO:Foraging:Foraging.py:log_git_hash:line 4807:Python version: 3.11.9 | packaged by Anaconda, Inc. | (main, Apr 19 2024, 16:40:41) [MSC v.1916 64 bit (AMD64)]
12:03:16 PM:INFO:Foraging:Foraging.py:log_git_hash:line 4824:Current git commit branch, hash: main, 698fb9fecded812fcf96d570658d9bc3766b14c6
12:03:16 PM:INFO:Foraging:Foraging.py:log_git_hash:line 4828:Current foraging_gui version: 1.6.19
12:03:16 PM:WARNING:Foraging:Foraging.py:log_git_hash:line 4838:local repository is clean
12:03:16 PM:INFO:Foraging:Foraging.py:<module>:line 4944:Setting QApplication attributes
12:03:16 PM:INFO:Foraging:Foraging.py:<module>:line 4952:Starting QApplication and Window
12:03:16 PM:INFO:Foraging:Foraging.py:__init__:line 77:Creating Window
12:03:16 PM:INFO:Foraging:Foraging.py:_GetSettings:line 1211:Loaded settings_box file
12:03:16 PM:ERROR:Foraging:Foraging.py:_GetSettings:line 1219:Settings box file does not have a newline at the end
12:03:16 PM:ERROR:Foraging:Foraging.py:exception_hook:line 4904:FATAL ERROR: 
Traceback (most recent call last):
  File "C:\Users\svc_aind_behavior\Documents\GitHub\dynamic-foraging-task\src\foraging_gui\Foraging.py", line 4959, in <module>
    win = Window(box_number=box_number,start_bonsai_ide=start_bonsai_ide)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\svc_aind_behavior\Documents\GitHub\dynamic-foraging-task\src\foraging_gui\Foraging.py", line 99, in __init__
    self._GetSettings()
  File "C:\Users\svc_aind_behavior\Documents\GitHub\dynamic-foraging-task\src\foraging_gui\Foraging.py", line 1220, in _GetSettings
    raise Exception('Settings box file does not have a newline at the end')
Exception: Settings box file does not have a newline at the end
```
</details>

**Comment by XX-Yin** [comment]
related to my testing. I should have delete this log file.
