### ISSUE TITLE
GUI complaining "Could not connect to device"

### ISSUE THREAD

**Issue by hagikent** [AllenNeuralDynamics/dynamic-foraging-task#1247]
At rig 428-9-A, there is no NewScaleMotor or AINDmotor but manual manipulator stages.
How can we work around the stage widget error?

____
09:50:42 AM:INFO:Foraging:Foraging.py:_InitializeMotorStage:line 912:Scanning for newscale stages
09:50:42 AM:INFO:Foraging:Foraging.py:_InitializeMotorStage:line 922:Could not find any instances of NewScale Stage
09:50:42 AM:INFO:Foraging:Foraging.py:_insert_stage_widget:line 279:Inserting Stage Widget
09:50:42 AM:INFO:connection:connection.py:_connect:line 688:Connecting to aibspi(10.128.108.106):2181, use_ssl: False
09:50:42 AM:INFO:client:client.py:_session_callback:line 561:Zookeeper connection established, state: CONNECTED
09:50:42 AM:INFO:connection:connection.py:_connect_attempt:line 655:Closing connection to aibspi:2181
09:50:42 AM:INFO:client:client.py:_session_callback:line 567:Zookeeper session closed, state: CLOSED
09:50:42 AM:INFO:main:main.py:get_stage_widget:line 23:Getting Stage Controller Widget - 1.0.4.dev1+g5cafa8d.b163669
09:50:42 AM:INFO:stepper_motor_device:stepper_motor_device.py:__init__:line 52:Skipping COM6 - device may be being used by another program
09:50:42 AM:INFO:stepper_motor_device:stepper_motor_device.py:__init__:line 52:Skipping COM11 - device may be being used by another program
09:50:42 AM:ERROR:stepper_motor_device:stepper_motor_device.py:__init__:line 67:Could not connect to device. Is the device connected or currently being used?
Encountered a fatal error:
Traceback (most recent call last):
  File "C:\Users\svc_aind_behavior\Documents\GitHub\dynamic-foraging-task\src\foraging_gui\Foraging.py", line 4959, in <module>
    win = Window(box_number=box_number,start_bonsai_ide=start_bonsai_ide)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\svc_aind_behavior\Documents\GitHub\dynamic-foraging-task\src\foraging_gui\Foraging.py", line 208, in __init__
    self._load_stage()
  File "C:\Users\svc_aind_behavior\Documents\GitHub\dynamic-foraging-task\src\foraging_gui\Foraging.py", line 269, in _load_stage
    self._insert_stage_widget(widget_to_replace)
  File "C:\Users\svc_aind_behavior\Documents\GitHub\dynamic-foraging-task\src\foraging_gui\Foraging.py", line 290, in _insert_stage_widget
    self.stage_widget = get_stage_widget()
                        ^^^^^^^^^^^^^^^^^^
  File "C:\Users\svc_aind_behavior\AppData\Local\Programs\Python\Python311\Lib\site-packages\StageWidget\main.py", line 24, in get_stage_widget
    return MainViewWidget(config)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\svc_aind_behavior\AppData\Local\Programs\Python\Python311\Lib\site-packages\StageWidget\views\widget\main_view.py", line 37, in __init__
    self.stage_model = StageModel(config)
                       ^^^^^^^^^^^^^^^^^^
  File "C:\Users\svc_aind_behavior\AppData\Local\Programs\Python\Python311\Lib\site-packages\StageWidget\models\stage_model.py", line 28, in __init__
    self.device = StepperMotorDevice(config=config)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\svc_aind_behavior\AppData\Local\Programs\Python\Python311\Lib\site-packages\StageWidget\models\stepper_motor_device.py", line 68, in __init__
    raise IOError("Could not connect to device. Is the device connected or currently being used?")
OSError: Could not connect to device. Is the device connected or currently being used?

09:50:42 AM:ERROR:Foraging:Foraging.py:exception_hook:line 4904:FATAL ERROR:
Traceback (most recent call last):
  File "C:\Users\svc_aind_behavior\Documents\GitHub\dynamic-foraging-task\src\foraging_gui\Foraging.py", line 4959, in <module>
    win = Window(box_number=box_number,start_bonsai_ide=start_bonsai_ide)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\svc_aind_behavior\Documents\GitHub\dynamic-foraging-task\src\foraging_gui\Foraging.py", line 208, in __init__
    self._load_stage()
  File "C:\Users\svc_aind_behavior\Documents\GitHub\dynamic-foraging-task\src\foraging_gui\Foraging.py", line 269, in _load_stage
    self._insert_stage_widget(widget_to_replace)
  File "C:\Users\svc_aind_behavior\Documents\GitHub\dynamic-foraging-task\src\foraging_gui\Foraging.py", line 290, in _insert_stage_widget
    self.stage_widget = get_stage_widget()
                        ^^^^^^^^^^^^^^^^^^
  File "C:\Users\svc_aind_behavior\AppData\Local\Programs\Python\Python311\Lib\site-packages\StageWidget\main.py", line 24, in get_stage_widget
    return MainViewWidget(config)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\svc_aind_behavior\AppData\Local\Programs\Python\Python311\Lib\site-packages\StageWidget\views\widget\main_view.py", line 37, in __init__
    self.stage_model = StageModel(config)
                       ^^^^^^^^^^^^^^^^^^
  File "C:\Users\svc_aind_behavior\AppData\Local\Programs\Python\Python311\Lib\site-packages\StageWidget\models\stage_model.py", line 28, in __init__
    self.device = StepperMotorDevice(config=config)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\svc_aind_behavior\AppData\Local\Programs\Python\Python311\Lib\site-packages\StageWidget\models\stepper_motor_device.py", line 68, in __init__
    raise IOError("Could not connect to device. Is the device connected or currently being used?")
OSError: Could not connect to device. Is the device connected or currently being used?

**Comment by XX-Yin** [comment]
I saw the same issue on my own computer. 

@hagikent Temporarily, adding a fake line ("newscale_serial_num_box1":123213) to the "ForagingSettings.json" to bypass this issue. 

@micahwoodard may help make a fix. Error is from a edge case from here https://github.com/AllenNeuralDynamics/dynamic-foraging-task/blob/main/src/foraging_gui/Foraging.py#L267

**Comment by hagikent** [comment]
thanks @XX-Yin will test it.

**Comment by hagikent** [comment]
@XX-Yin 's workaround worked. 
Still it would be great to fix this @micahwoodard to make it less hacky! 
Way less urgent but keep this ticket open.

**Comment by alexpiet** [comment]
I see. Right now the GUI assumes if the NewScale isn't present then you are using a AIND motor stage. 
- @XX-Yin @galenlynch Are you planning on continuing to use the NewScale stage in the ephys rigs? They are being removed from 447. I'm asking to determine if this is a good time to revamp motor stage things in general.
- We can configure things to either have a setting for "no motor stage" or you have to explicitly say you are using the AIND motor stage. @micahwoodard Are there any edge cases we need to think about? Session/rig metadata needs to cover this non-motor stage.

**Comment by XX-Yin** [comment]
@alexpiet The new stage causes artifacts on ephys rig. We will keep the new scale stage until we find a clear reason to replace it.

For the "no motor stage", the code can detect this condition.

**Comment by ellahiltonvano** [comment]
@alexpiet previously assigned to Micah
