### ISSUE TITLE
Error in camera Preview

### ISSUE THREAD

**Issue by hagikent** [AllenNeuralDynamics/dynamic-foraging-task#1249]
In one rig (428-9-B), when I hit Preview, I see the following error. 
Any clue @XX-Yin @ZhixiaoSu ?

The FLIR cameras are connected, recognized, set-up, and properly running.

_____
Traceback (most recent call last):
  File "C:\Users\svc_aind_behavior\Documents\GitHub\dynamic-foraging-task\src\foraging_gui\Dialogs.py", line 1206, in _start_preview
    self.MainWindow.Channel.CameraStartType(int(2))
  File "C:\Users\svc_aind_behavior\Documents\GitHub\dynamic-foraging-task\src\foraging_gui\rigcontrol.py", line 226, in CameraStartType
    self.send("/camerastarttype", value)
  File "C:\Users\svc_aind_behavior\Documents\GitHub\dynamic-foraging-task\src\foraging_gui\rigcontrol.py", line 60, in send
    return self.client.sendOSC(message)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\svc_aind_behavior\AppData\Local\miniconda3\envs\Foraging\Lib\site-packages\pyOSC3\OSC3.py", line 2869, in sendOSC
    txOk = self._transmitMsgWithTimeout(msg)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\svc_aind_behavior\AppData\Local\miniconda3\envs\Foraging\Lib\site-packages\pyOSC3\OSC3.py", line 2857, in _transmitMsgWithTimeout
    len_big_endian = array.array('c', '\0' * 4)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: cannot use a str to initialize an array with typecode 'c'

**Comment by XX-Yin** [comment]
I have no idea. And I can help take a look if you are in this institute.

**Comment by hagikent** [comment]
would be great, I will be around this week except 12/27. Will ping!

**Comment by XX-Yin** [comment]
> would be great, I will be around this week except 12/27. Will ping!

I may not be in this institute on 12/27

**Comment by ellahiltonvano** [comment]
@hagikent were you able to resolve this?

**Comment by hagikent** [comment]
Still persists... @XX-Yin can we quickly have look tomorrow?

**Comment by ellahiltonvano** [comment]
@hagikent did you and Xinxin get a chance to resolve this?

**Comment by hagikent** [comment]
No. I'm setting the rig up from scratch again. If that solves this issue, I will close the thread. 
Keeping this open for tracking purpose would be great.

**Comment by ellahiltonvano** [comment]
@hagikent great, I'll leave it open, thanks for the update!
