### ISSUE TITLE
FATAL:json.decoder.JSONDecodeError: ('Could not load settings file at: C:\\Users\\svc_aind_behavior\\Documents\\ForagingSettings\\ForagingSettings.json', 'Invalid \\escape: line 10 column 28 (char 460)')

### ISSUE THREAD

**Issue by alexpiet** [AllenNeuralDynamics/dynamic-foraging-task#1254]
This issue was automatically generated from GUI logs.<br><br>file: Foraging.py<br>function: exception_hook<br>line 4904<br>logfile: W10DT714669/W10DT714669-B_gui_log_2024-12-23_10-50-37.txt<br>boxes: 9B<br>count: 3<br>text: FATAL:json.decoder.JSONDecodeError: ('Could not load settings file at: C:\\Users\\svc_aind_behavior\\Documents\\ForagingSettings\\ForagingSettings.json', 'Invalid \\escape: line 10 column 28 (char 460)')<br><details><summary> GUI Log snippet (click for full log)

```
  File "C:\Users\svc_aind_behavior\Documents\GitHub\dynamic-foraging-task\src\foraging_gui\Foraging.py", line 99, in __init__
    self._GetSettings()
  File "C:\Users\svc_aind_behavior\Documents\GitHub\dynamic-foraging-task\src\foraging_gui\Foraging.py", line 1243, in _GetSettings
    raise e
  File "C:\Users\svc_aind_behavior\Documents\GitHub\dynamic-foraging-task\src\foraging_gui\Foraging.py", line 1238, in _GetSettings
    self.Settings = json.load(f)
                    ^^^^^^^^^^^^
  File "C:\Users\svc_aind_behavior\AppData\Local\miniconda3\envs\Foraging\Lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "C:\Users\svc_aind_behavior\AppData\Local\miniconda3\envs\Foraging\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\svc_aind_behavior\AppData\Local\miniconda3\envs\Foraging\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\svc_aind_behavior\AppData\Local\miniconda3\envs\Foraging\Lib\json\decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
               ^^^^^^^^^^^^^^^^^^^^^^
json.decoder.JSONDecodeError: ('Could not load settings file at: C:\\Users\\svc_aind_behavior\\Documents\\ForagingSettings\\ForagingSettings.json', 'Invalid \\escape: line 10 column 28 (char 460)')
```
</summary>
Full GUI log 

```
10:50:37 AM:INFO:Foraging:Foraging.py:start_gui_log_file:line 4796:Starting logfile!
10:50:38 AM:INFO:Foraging:Foraging.py:log_git_hash:line 4807:Python version: 3.11.11 | packaged by Anaconda, Inc. | (main, Dec 11 2024, 16:34:19) [MSC v.1929 64 bit (AMD64)]
10:50:38 AM:INFO:Foraging:Foraging.py:log_git_hash:line 4824:Current git commit branch, hash: main, 698fb9fecded812fcf96d570658d9bc3766b14c6
10:50:38 AM:INFO:Foraging:Foraging.py:log_git_hash:line 4828:Current foraging_gui version: 1.6.19
10:50:38 AM:WARNING:Foraging:Foraging.py:log_git_hash:line 4838:local repository is clean
10:50:38 AM:INFO:Foraging:Foraging.py:<module>:line 4944:Setting QApplication attributes
10:50:38 AM:INFO:Foraging:Foraging.py:<module>:line 4952:Starting QApplication and Window
10:50:38 AM:INFO:Foraging:Foraging.py:__init__:line 77:Creating Window
10:50:38 AM:INFO:Foraging:Foraging.py:_GetSettings:line 1211:Loaded settings_box file
10:50:38 AM:ERROR:Foraging:Foraging.py:_GetSettings:line 1241:Could not load settings file at: C:\Users\svc_aind_behavior\Documents\ForagingSettings\ForagingSettings.json, Invalid \escape: line 10 column 28 (char 460)
10:50:38 AM:ERROR:Foraging:Foraging.py:exception_hook:line 4904:FATAL ERROR: 
Traceback (most recent call last):
  File "C:\Users\svc_aind_behavior\Documents\GitHub\dynamic-foraging-task\src\foraging_gui\Foraging.py", line 4959, in <module>
    win = Window(box_number=box_number,start_bonsai_ide=start_bonsai_ide)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\svc_aind_behavior\Documents\GitHub\dynamic-foraging-task\src\foraging_gui\Foraging.py", line 99, in __init__
    self._GetSettings()
  File "C:\Users\svc_aind_behavior\Documents\GitHub\dynamic-foraging-task\src\foraging_gui\Foraging.py", line 1243, in _GetSettings
    raise e
  File "C:\Users\svc_aind_behavior\Documents\GitHub\dynamic-foraging-task\src\foraging_gui\Foraging.py", line 1238, in _GetSettings
    self.Settings = json.load(f)
                    ^^^^^^^^^^^^
  File "C:\Users\svc_aind_behavior\AppData\Local\miniconda3\envs\Foraging\Lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "C:\Users\svc_aind_behavior\AppData\Local\miniconda3\envs\Foraging\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\svc_aind_behavior\AppData\Local\miniconda3\envs\Foraging\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\svc_aind_behavior\AppData\Local\miniconda3\envs\Foraging\Lib\json\decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
               ^^^^^^^^^^^^^^^^^^^^^^
json.decoder.JSONDecodeError: ('Could not load settings file at: C:\\Users\\svc_aind_behavior\\Documents\\ForagingSettings\\ForagingSettings.json', 'Invalid \\escape: line 10 column 28 (char 460)')
```
</details>

**Comment by ellahiltonvano** [comment]
@hagikent
