### ISSUE TITLE
Optogenetics errors

### ISSUE THREAD

**Issue by alexpiet** [AllenNeuralDynamics/dynamic-foraging-task#409]
There are several errors that I think are related to optogenetics

06:03:05 PM:ERROR:Dialogs:Dialogs.py:_Frequency:line 247:''
06:03:05 PM:ERROR:Dialogs:Dialogs.py:_Frequency:line 247:'Left'
06:03:05 PM:ERROR:Foraging:Foraging.py:exception_hook:line 3583:FATAL ERROR: 
Traceback (most recent call last):
  File "C:\Users\svc_aind_behavior\Documents\GitHub\dynamic-foraging-task\src\foraging_gui\Dialogs.py", line 192, in _Laser_1
    self._Laser(1)
  File "C:\Users\svc_aind_behavior\Documents\GitHub\dynamic-foraging-task\src\foraging_gui\Dialogs.py", line 321, in _Laser
    for i in range(len(RecentLaserCalibration[Color][Protocol][CurrentFrequency]['Left']['LaserPowerVoltage'])):
KeyError: 'Left'

06:03:17 PM:ERROR:Dialogs:Dialogs.py:_Frequency:line 247:''
06:03:17 PM:ERROR:Dialogs:Dialogs.py:_Frequency:line 247:'Left'
06:03:17 PM:ERROR:Foraging:Foraging.py:exception_hook:line 3583:FATAL ERROR: 
Traceback (most recent call last):
  File "C:\Users\svc_aind_behavior\Documents\GitHub\dynamic-foraging-task\src\foraging_gui\Dialogs.py", line 192, in _Laser_1
    self._Laser(1)
  File "C:\Users\svc_aind_behavior\Documents\GitHub\dynamic-foraging-task\src\foraging_gui\Dialogs.py", line 321, in _Laser
    for i in range(len(RecentLaserCalibration[Color][Protocol][CurrentFrequency]['Left']['LaserPowerVoltage'])):
KeyError: 'Left'

06:03:42 PM:ERROR:Dialogs:Dialogs.py:_Frequency:line 247:''
06:03:42 PM:ERROR:Dialogs:Dialogs.py:_Frequency:line 247:'Left'
06:03:42 PM:ERROR:Foraging:Foraging.py:exception_hook:line 3583:FATAL ERROR: 
Traceback (most recent call last):
  File "C:\Users\svc_aind_behavior\Documents\GitHub\dynamic-foraging-task\src\foraging_gui\Dialogs.py", line 192, in _Laser_1
    self._Laser(1)
  File "C:\Users\svc_aind_behavior\Documents\GitHub\dynamic-foraging-task\src\foraging_gui\Dialogs.py", line 321, in _Laser
    for i in range(len(RecentLaserCalibration[Color][Protocol][CurrentFrequency]['Left']['LaserPowerVoltage'])):
KeyError: 'Left'

**Comment by XX-Yin** [comment]
This is caused by me during testing. 'Left' in the laser calibration file should be changed to 'Laser_1', and 'Right' to 'Laser_2'.

**Comment by alexpiet** [comment]
Closing because we fixed the laser names
