### ISSUE TITLE
Camera Check for drop frames is unstable: Python integer 36287966 out of bounds for uint8

### ISSUE THREAD

**Issue by alexpiet** [AllenNeuralDynamics/dynamic-foraging-task#547]
The following error message was generated several times last week. It appears something in how check_drop_frames works is unstable with (I assume) long video recordings. 

@XX-Yin 

09:58:45 AM:ERROR:Foraging:Foraging.py:exception_hook:line 4096:FATAL ERROR: 
Traceback (most recent call last):
  File "C:\Users\svc_aind_ephys\Documents\GitHub\dynamic-foraging-task\src\foraging_gui\Foraging.py", line 2534, in _OpenLast
    self._Open(open_last=True)
  File "C:\Users\svc_aind_ephys\Documents\GitHub\dynamic-foraging-task\src\foraging_gui\Foraging.py", line 2858, in _Open
    self._check_drop_frames(save_tag=0)
  File "C:\Users\svc_aind_ephys\Documents\GitHub\dynamic-foraging-task\src\foraging_gui\Foraging.py", line 512, in _check_drop_frames
    triggers = harp.read(camera_trigger_file)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\svc_aind_ephys\.conda\envs\Foraging\Lib\site-packages\harp\io.py", line 85, in read
    nrows = len(data) // stride
            ~~~~~~~~~~^^~~~~~~~
OverflowError: Python integer 36287966 out of bounds for uint8

**Comment by XX-Yin** [comment]
@alexpiet Was it on 323_EPHYS1? It was related to the python package. We fixed (@KanghoonJ) this issue by reinstalling the python packages.

**Comment by alexpiet** [comment]
Yes, it was on EPHYS1. I will close the issue if you resolved the issue.

**Comment by XX-Yin** [comment]
> Yes, it was on EPHYS1. I will close the issue if you resolved the issue.

Yes, we can close it.
