### ISSUE TITLE
AttributeError: 'Window' object has no attribute 'SaveFileJson'

### ISSUE THREAD

**Issue by alexpiet** [AllenNeuralDynamics/dynamic-foraging-task#750]
This issue was automatically generated from GUI logs.<br><br>file: Foraging.py<br>function: _OpenBehaviorFolder<br>line 1725<br>logfile: W10DT713883/W10DT713883-A_gui_log_2024-10-02_11-13-46.txt<br>boxes: ephys3<br>count: 1<br>text: AttributeError: 'Window' object has no attribute 'SaveFileJson'<br><br><br>Log context<br>

```
11:14:16 AM:INFO:Foraging:Foraging.py:keyPressEvent:line 1944:Changing parameter: LeftValue_volume, 3.0 -> 2.0
11:14:16 AM:INFO:Foraging:Foraging.py:keyPressEvent:line 1885:processing parameter changes
11:14:16 AM:INFO:Foraging:Foraging.py:keyPressEvent:line 1944:Changing parameter: ID, 0.0 -> 753125.0
11:14:16 AM:INFO:Foraging:Foraging.py:keyPressEvent:line 1944:Changing parameter: BaseWeight,  -> 25.57
11:14:16 AM:INFO:Foraging:Foraging.py:keyPressEvent:line 1944:Changing parameter: TargetWeight,  -> 21.734
11:14:16 AM:INFO:Foraging:Foraging.py:keyPressEvent:line 1944:Changing parameter: PositionY, 10113.5 -> 10113.0
11:14:16 AM:INFO:Foraging:Foraging.py:keyPressEvent:line 1944:Changing parameter: PositionX, 5113.5 -> 4902.0
11:14:17 AM:INFO:Foraging:Foraging.py:keyPressEvent:line 1885:processing parameter changes
11:14:17 AM:INFO:Foraging:Foraging.py:keyPressEvent:line 1885:processing parameter changes
11:14:17 AM:INFO:Foraging:Foraging.py:keyPressEvent:line 1885:processing parameter changes
11:14:17 AM:INFO:Foraging:Foraging.py:keyPressEvent:line 1885:processing parameter changes
11:14:17 AM:INFO:Foraging:Foraging.py:keyPressEvent:line 1885:processing parameter changes
11:14:17 AM:INFO:Foraging:Foraging.py:keyPressEvent:line 1885:processing parameter changes
11:14:17 AM:INFO:Foraging:Foraging.py:keyPressEvent:line 1885:processing parameter changes
11:14:18 AM:INFO:Foraging:Foraging.py:keyPressEvent:line 1885:processing parameter changes
11:14:23 AM:INFO:Foraging:Foraging.py:keyPressEvent:line 1885:processing parameter changes
11:14:23 AM:INFO:Dialogs:Dialogs.py:update_auto_train_lock:line 2922:AutoTrain disengaged!
11:14:23 AM:INFO:curriculum_manager:curriculum_manager.py:get_curriculum:line 131:Loaded a DynamicForagingCurriculum model from 'Uncoupled Baiting_curriculum_v2.3_schema_v1.0.json'.
11:14:23 AM:INFO:Dialogs:Dialogs.py:_override_curriculum_clicked:line 2718:Override stage clicked: state=0
11:14:23 AM:INFO:Dialogs:Dialogs.py:_update_curriculum_diagrams:line 2664:Selected curriculum: {'curriculum_name': 'Uncoupled Baiting', 'curriculum_version': '2.3', 'curriculum_schema_version': '1.0', 'curriculum_description': '2024-08-16 max_len = 75 mins; decrease finished trial criterion'}
11:14:23 AM:INFO:curriculum_manager:curriculum_manager.py:get_curriculum:line 131:Loaded a DynamicForagingCurriculum model from 'Uncoupled Baiting_curriculum_v2.3_schema_v1.0.json'.
11:14:23 AM:INFO:Dialogs:Dialogs.py:_update_stage_to_apply:line 2744:Current stage to apply: GRADUATED @Uncoupled Baiting (v2.3@1.0)
11:14:23 AM:INFO:Dialogs:Dialogs.py:_update_stage_to_apply:line 2744:Current stage to apply: GRADUATED @Uncoupled Baiting (v2.3@1.0)
11:14:23 AM:INFO:Dialogs:Dialogs.py:_update_curriculum_diagrams:line 2664:Selected curriculum: {'curriculum_name': 'Uncoupled Baiting', 'curriculum_version': '2.3', 'curriculum_schema_version': '1.0', 'curriculum_description': '2024-08-16 max_len = 75 mins; decrease finished trial criterion'}
11:14:23 AM:INFO:curriculum_manager:curriculum_manager.py:get_curriculum:line 131:Loaded a DynamicForagingCurriculum model from 'Uncoupled Baiting_curriculum_v2.3_schema_v1.0.json'.
11:14:26 AM:ERROR:Foraging:Foraging.py:_OpenBehaviorFolder:line 1725:Traceback (most recent call last):
  File "C:\Users\svc_aind_ephys\Documents\GitHub\dynamic-foraging-task\src\foraging_gui\Foraging.py", line 1722, in _OpenBehaviorFolder
    folder_name=os.path.dirname(self.SaveFileJson)
                                ^^^^^^^^^^^^^^^^^
AttributeError: 'Window' object has no attribute 'SaveFileJson'
```

**Comment by alexpiet** [comment]
This issue reoccurred:<br><br>file: Foraging.py<br>function: _OpenBehaviorFolder<br>line 1759<br>logfile: W10DT713669/W10DT713669-A_gui_log_2024-11-04_13-44-55.txt<br>boxes: ephys1<br>count: 2<br>text: AttributeError: 'Window' object has no attribute 'SaveFileJson'<br><br><br>Log context<br>

```
01:45:01 PM:INFO:Foraging:Foraging.py:_load_most_recent_rig_json:line 1564:Found existing rig.json: rig_323_EPHYS1_2024-06-17.json
01:45:01 PM:INFO:Foraging:Foraging.py:keyPressEvent:line 1919:processing parameter changes
01:45:01 PM:INFO:Foraging:Foraging.py:keyPressEvent:line 1978:Changing parameter: RightValue, 0.03 -> 0.036
01:45:01 PM:INFO:Foraging:Foraging.py:keyPressEvent:line 1978:Changing parameter: LeftValue, 0.03 -> 0.04
01:45:01 PM:INFO:Foraging:Foraging.py:keyPressEvent:line 1978:Changing parameter: RightValue, 0.03 -> 0.036
01:45:01 PM:INFO:Foraging:Foraging.py:keyPressEvent:line 1978:Changing parameter: LeftValue, 0.03 -> 0.04
01:45:01 PM:INFO:Foraging:Foraging.py:keyPressEvent:line 1978:Changing parameter: GiveWaterL, 0.03 -> 0.04
01:45:01 PM:INFO:Foraging:Foraging.py:keyPressEvent:line 1978:Changing parameter: GiveWaterR, 0.03 -> 0.036
01:45:01 PM:INFO:Foraging:Foraging.py:keyPressEvent:line 1919:processing parameter changes
01:45:01 PM:INFO:Foraging:Foraging.py:keyPressEvent:line 1919:processing parameter changes
01:45:01 PM:INFO:Foraging:Foraging.py:keyPressEvent:line 1919:processing parameter changes
01:45:01 PM:INFO:Foraging:Foraging.py:keyPressEvent:line 1919:processing parameter changes
01:45:01 PM:WARNING:Foraging:Foraging.py:_show_disk_space:line 219:Low disk space  Used space: 1705.51GB    Free space: 157.50GB
01:45:01 PM:INFO:Foraging:Foraging.py:__init__:line 203:Start up complete
01:45:03 PM:INFO:aws_util:aws_util.py:import_df_from_s3:line 115:Dataframe imported from s3://aind-behavior-data/foraging_nwb_bonsai_processed/df_sessions.pkl, len(df) = 5170
01:45:04 PM:INFO:aws_util:aws_util.py:import_df_from_s3:line 115:Dataframe imported from s3://aind-behavior-data/foraging_auto_training/df_manager_447_demo.pkl, len(df) = 3743
01:45:04 PM:INFO:aws_util:aws_util.py:download_dir_from_s3:line 140:134 objects downloaded from s3://aind-behavior-data/foraging_auto_training/saved_curriculums/ to C:\Users\svc_aind_ephys/capsule/scratch/saved_curriculums/
01:45:04 PM:INFO:curriculum_manager:curriculum_manager.py:download_curriculums:line 162:Found 29 curriculums in C:\Users\svc_aind_ephys/capsule/scratch/saved_curriculums/
01:45:05 PM:INFO:aws_util:aws_util.py:download_dir_from_s3:line 140:134 objects downloaded from s3://aind-behavior-data/foraging_auto_training/saved_curriculums/ to C:\Users\svc_aind_ephys/.aind_auto_train/curriculum_manager/
01:45:05 PM:INFO:curriculum_manager:curriculum_manager.py:download_curriculums:line 162:Found 29 curriculums in C:\Users\svc_aind_ephys/.aind_auto_train/curriculum_manager/
01:45:05 PM:INFO:Dialogs:Dialogs.py:update_auto_train_fields:line 2397:No entry found in df_training_manager for subject_id: 0
01:45:05 PM:INFO:Dialogs:Dialogs.py:_override_curriculum_clicked:line 2745:Override stage clicked: state=2
01:45:05 PM:INFO:Dialogs:Dialogs.py:_update_stage_to_apply:line 2771:Current stage to apply: unknown training stage @unknown curriculum
01:45:10 PM:INFO:Foraging:Foraging.py:_StopCurrentSession:line 3671:Stopping current trials
01:45:14 PM:INFO:Foraging:Foraging.py:_Open:line 2995:Quick load failed, user hit cancel or X
01:45:16 PM:ERROR:Foraging:Foraging.py:_OpenBehaviorFolder:line 1759:Traceback (most recent call last):
  File "C:\Users\svc_aind_ephys\Documents\GitHub\dynamic-foraging-task\src\foraging_gui\Foraging.py", line 1756, in _OpenBehaviorFolder
    folder_name=os.path.dirname(self.SaveFileJson)
                                ^^^^^^^^^^^^^^^^^
AttributeError: 'Window' object has no attribute 'SaveFileJson'
```

**Comment by alexpiet** [comment]
@micahwoodard It looks like the "open behavior folder" function throughs an error, maybe when the session hasn't run yet. Can you take a look?

Options - 
- remove the OpenBehaviorFolder
- check for this case of the session hasn't started yet

**Comment by micahwoodard** [comment]
It seems like the [_OpenBehaviorFolder](https://github.com/AllenNeuralDynamics/dynamic-foraging-task/blob/4f4f59556389b4696a28bcbed810dec00816cf61/src/foraging_gui/Foraging.py#L1714C3-L1725C54) is in a try/except. Do we want to change it to something like: 
```
if hasattr(self, 'SAveFileJson'): 
   subprocess.Popen(['explorer', os.path.dirname(self.SaveFileJson)])
elif hasattr(self, 'default_saveFolder'):
   subprocess.Popen(['explorer', self.default_saveFolder, self.current_box, self.ID.text()])
else: 
   logging.info('Save folder unspecified')
```

or do we want to try and not call this function before those attributes are set?

**Comment by alexpiet** [comment]
The save folder is something like `C:/behavior_data/<rig name>/<mouse>/<session>`. So if there isn't a save folder location, then I would open to `C:/behavior_data/`

**Comment by micahwoodard** [comment]
Based on the logs it seems like it's always able to execute the [second try/except](https://github.com/AllenNeuralDynamics/dynamic-foraging-task/blob/4f4f59556389b4696a28bcbed810dec00816cf61/src/foraging_gui/Foraging.py#L1721C1-L1723C61) that uses AnimalFolder=os.path.join(self.default_saveFolder, self.current_box, self.ID.text()) which seems to be `C:/behavior_data/<rig name>/<mouse>/`. Should I keep that or still go to` C:/behavior_data/`?

**Comment by alexpiet** [comment]
> Based on the logs it seems like it's always able to execute the [second try/except](https://github.com/AllenNeuralDynamics/dynamic-foraging-task/blob/4f4f59556389b4696a28bcbed810dec00816cf61/src/foraging_gui/Foraging.py#L1721C1-L1723C61) that uses AnimalFolder=os.path.join(self.default_saveFolder, self.current_box, self.ID.text()) which seems to be `C:/behavior_data/<rig name>/<mouse>/`. Should I keep that or still go to` C:/behavior_data/`?

Yeah, thats fine
