### ISSUE TITLE
ValueError: time data '2024-10-04 13:41:09' does not match format '%Y-%m-%d %H:%M:%S.%f'

### ISSUE THREAD

**Issue by alexpiet** [AllenNeuralDynamics/dynamic-foraging-task#754]
This issue was automatically generated from GUI logs.<br><br>file: Foraging.py<br>function: _Save<br>line 2700<br>logfile: W10DT714086/W10DT714086-D_gui_log_2024-10-04_13-06-26.txt<br>boxes: 1D<br>count: 1<br>text: ValueError: time data '2024-10-04 13:41:09' does not match format '%Y-%m-%d %H:%M:%S.%f'<br><br><br>Log context<br>

```
01:41:09 PM:INFO:rigcontrol:rigcontrol.py:msg_handler:line 56:['/TrialStartTime', 23146686.301984, '127.0.0.1', 4032]
01:41:09 PM:INFO:rigcontrol:rigcontrol.py:msg_handler:line 56:['/ITIStartTimeHarp', 23146686.306496, '127.0.0.1', 4032]
01:41:09 PM:WARNING:warnings:warnings.py:_showwarnmsg:line 110:C:\Users\svc_aind_behavior\Documents\GitHub\dynamic-foraging-task\src\foraging_gui\Visualization.py:172: RuntimeWarning: Mean of empty slice
  RewardedHistoryF[i+1-kernel_size]=np.nanmean(RewardedHistoryT[i+1-kernel_size:i+1])

01:41:09 PM:INFO:Foraging:Foraging.py:_Save:line 2457:Saving current session, ForceSave=1
01:41:09 PM:INFO:Foraging:Foraging.py:_GetWaterCalibration:line 1015:Loaded Water Calibration
01:41:09 PM:INFO:GenerateMetadata:GenerateMetadata.py:__init__:line 91:processing:C:\behavior_data\447-1-D\746716\behavior_746716_2024-10-04_13-30-29
01:41:09 PM:INFO:GenerateMetadata:GenerateMetadata.py:_handle_edge_cases:line 399:Cannot log reward delivery in session metadata - missing fields
01:41:09 PM:INFO:GenerateMetadata:GenerateMetadata.py:_get_reward_delivery:line 1237:No reward delivery metadata found!
01:41:09 PM:INFO:GenerateMetadata:GenerateMetadata.py:_get_opto_calibration:line 1072:No opto calibration results detected!
01:41:09 PM:INFO:rigcontrol:rigcontrol.py:msg_handler:line 56:['/LeftLickTime', 23146686.477248, '127.0.0.1', 4033]
01:41:09 PM:ERROR:Foraging:Foraging.py:_Save:line 2699:Error generating session metadata: time data '2024-10-04 13:41:09' does not match format '%Y-%m-%d %H:%M:%S.%f'
01:41:09 PM:ERROR:Foraging:Foraging.py:_Save:line 2700:Traceback (most recent call last):
  File "C:\Users\svc_aind_behavior\Documents\GitHub\dynamic-foraging-task\src\foraging_gui\Foraging.py", line 2681, in _Save
    generated_metadata=generate_metadata(Obj=Obj)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\svc_aind_behavior\Documents\GitHub\dynamic-foraging-task\src\foraging_gui\GenerateMetadata.py", line 115, in __init__
    self._session()
  File "C:\Users\svc_aind_behavior\Documents\GitHub\dynamic-foraging-task\src\foraging_gui\GenerateMetadata.py", line 544, in _session
    self._get_behavior_stream()
  File "C:\Users\svc_aind_behavior\Documents\GitHub\dynamic-foraging-task\src\foraging_gui\GenerateMetadata.py", line 1039, in _get_behavior_stream
    stream_end_time=datetime.strptime(self.Obj['Other_CurrentTime'], '%Y-%m-%d %H:%M:%S.%f'),
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\svc_aind_behavior\AppData\Local\miniconda3\envs\Foraging\Lib\_strptime.py", line 567, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\svc_aind_behavior\AppData\Local\miniconda3\envs\Foraging\Lib\_strptime.py", line 349, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data '2024-10-04 13:41:09' does not match format '%Y-%m-%d %H:%M:%S.%f'
```

**Comment by ellahiltonvano** [comment]
> 1 month old and has not reoccurred, closing the issue
