### ISSUE TITLE
ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it

### ISSUE THREAD

**Issue by alexpiet** [AllenNeuralDynamics/dynamic-foraging-task#760]
This issue was automatically generated from GUI logs.<br><br>file: Foraging.py<br>function: _StartEphysRecording<br>line 428<br>logfile: W10DT713883/W10DT713883-A_gui_log_2024-10-03_11-02-49.txt<br>boxes: ephys3<br>count: 1<br>text: ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it<br><br><br>Log context<br>

```
12:14:30 PM:INFO:Foraging:Foraging.py:log_subprocess_output:line 4741:BONSAI: frame=2125148 fps=500 q=28.0 Lsize=26065393KiB time=01:10:50.29 bitrate=50238.3kbits/s speed=0.999x
12:14:30 PM:INFO:Foraging:Foraging.py:log_subprocess_output:line 4741:BONSAI: 
12:14:30 PM:INFO:Foraging:Foraging.py:log_subprocess_output:line 4741:BONSAI: 
12:14:30 PM:INFO:Foraging:Foraging.py:log_subprocess_output:line 4741:BONSAI: [out#0/avi @ 000002181fab8940] video:26031192KiB audio:0KiB subtitle:0KiB other streams:0KiB global headers:0KiB muxing overhead: 0.136699%
12:14:30 PM:INFO:Foraging:Foraging.py:log_subprocess_output:line 4741:BONSAI: frame=2125148 fps=500 q=28.0 Lsize=26066777KiB time=01:10:50.29 bitrate=50241.0kbits/s speed=0.999x
12:14:30 PM:INFO:Foraging:Foraging.py:log_subprocess_output:line 4741:BONSAI: 
12:14:30 PM:INFO:Foraging:Foraging.py:log_subprocess_output:line 4741:BONSAI: 
12:14:30 PM:INFO:Foraging:Foraging.py:log_subprocess_output:line 4741:BONSAI: [out#0/avi @ 000001c1a348b180] video:26029574KiB audio:0KiB subtitle:0KiB other streams:0KiB global headers:0KiB muxing overhead: 0.136701%
12:14:30 PM:INFO:Foraging:Foraging.py:log_subprocess_output:line 4741:BONSAI: frame=2125148 fps=500 q=27.0 Lsize=26065156KiB time=01:10:50.29 bitrate=50237.9kbits/s speed=0.999x
12:14:30 PM:INFO:Foraging:Foraging.py:log_subprocess_output:line 4741:BONSAI: 
12:14:30 PM:INFO:Foraging:Foraging.py:log_subprocess_output:line 4741:BONSAI: 
12:14:37 PM:INFO:GenerateMetadata:GenerateMetadata.py:__init__:line 91:processing:D:\BehaviorData\323_EPHYS3\753122\behavior_753122_2024-10-03_11-03-29
12:14:37 PM:INFO:GenerateMetadata:GenerateMetadata.py:_handle_edge_cases:line 399:Cannot log reward delivery in session metadata - missing fields
12:14:37 PM:INFO:GenerateMetadata:GenerateMetadata.py:_get_reward_delivery:line 1237:No reward delivery metadata found!
12:14:37 PM:INFO:GenerateMetadata:GenerateMetadata.py:_FindLatestCalibrationDate:line 1174:No dates found in the LaserCalibrationResults.
12:14:37 PM:INFO:GenerateMetadata:GenerateMetadata.py:_FindLatestCalibrationDate:line 1174:No dates found in the LaserCalibrationResults.
12:14:37 PM:INFO:GenerateMetadata:GenerateMetadata.py:_get_ephys_stream:line 909:No ephys data stream detected!
12:14:37 PM:INFO:GenerateMetadata:GenerateMetadata.py:_get_ophys_stream:line 628:No photometry data stream detected!
12:14:37 PM:INFO:GenerateMetadata:GenerateMetadata.py:__init__:line 118:Session metadata generated successfully: True
12:14:37 PM:INFO:GenerateMetadata:GenerateMetadata.py:__init__:line 119:Rig metadata generated successfully: True
12:14:37 PM:INFO:GenerateMetadata:GenerateMetadata.py:__init__:line 120:Data description generated successfully: True
12:14:51 PM:ERROR:Foraging:Foraging.py:_StartEphysRecording:line 428:Traceback (most recent call last):
  File "C:\Users\svc_aind_ephys\Anaconda3\envs\Foraging\Lib\site-packages\urllib3\connection.py", line 196, in _new_conn
    sock = connection.create_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\svc_aind_ephys\Anaconda3\envs\Foraging\Lib\site-packages\urllib3\util\connection.py", line 85, in create_connection
    raise err
  File "C:\Users\svc_aind_ephys\Anaconda3\envs\Foraging\Lib\site-packages\urllib3\util\connection.py", line 73, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it
```

**Comment by ellahiltonvano** [comment]
> 1 month old and has not reoccurred, closing the issue
