### ISSUE TITLE
FATAL:AttributeError: 'NoneType' object has no attribute 'curriculum_name'

### ISSUE THREAD

**Issue by alexpiet** [AllenNeuralDynamics/dynamic-foraging-task#764]
This issue was automatically generated from GUI logs.<br><br>file: Foraging.py<br>function: exception_hook<br>line 4746<br>logfile: W10DT714084/W10DT714084-A_gui_log_2024-10-07_15-54-34.txt<br>boxes: 2A<br>count: 2<br>text: FATAL:AttributeError: 'NoneType' object has no attribute 'curriculum_name'<br><br><br>Log context<br>

```
04:35:13 PM:INFO:Foraging:Foraging.py:keyPressEvent:line 1933:Changing parameter: ID, 0.0 -> 747890.0
04:35:13 PM:INFO:Foraging:Foraging.py:keyPressEvent:line 1933:Changing parameter: PositionZ, 4303.5 -> 2702.5
04:35:13 PM:INFO:Foraging:Foraging.py:keyPressEvent:line 1933:Changing parameter: PositionY, 10577.0 -> 13977.0
04:35:13 PM:INFO:Foraging:Foraging.py:keyPressEvent:line 1933:Changing parameter: PositionX, 8481.5 -> 9682.0
04:35:13 PM:INFO:Foraging:Foraging.py:keyPressEvent:line 1933:Changing parameter: Step, 200.0 -> 50.0
04:35:15 PM:INFO:Foraging:Foraging.py:_Start:line 3750:Start button pressed: starting trial loop
04:35:15 PM:INFO:Foraging:Foraging.py:keyPressEvent:line 1874:processing parameter changes
04:35:16 PM:INFO:Foraging:Foraging.py:_Start:line 3816:Starting session, with experimenter: Bowen Tan
04:35:16 PM:INFO:Foraging:Foraging.py:_Start:line 3923:Setting Project name: Behavior Platform
04:35:16 PM:INFO:Foraging:Foraging.py:keyPressEvent:line 1874:processing parameter changes
04:35:16 PM:INFO:Foraging:Foraging.py:keyPressEvent:line 1874:processing parameter changes
04:35:16 PM:INFO:Foraging:Foraging.py:_restartlogging:line 937:Restarting logging
04:35:16 PM:INFO:Foraging:Foraging.py:_GetSaveFolder:line 2755:Created new folder: C:\behavior_data\447-2-A\747890\behavior_747890_2024-10-07_16-35-16
04:35:16 PM:INFO:Foraging:Foraging.py:_GetSaveFolder:line 2758:Created new folder: C:\behavior_data\447-2-A\747890\behavior_747890_2024-10-07_16-35-16\metadata-dir
04:35:16 PM:INFO:Foraging:Foraging.py:_GetSaveFolder:line 2761:Created new folder: C:\behavior_data\447-2-A\747890\behavior_747890_2024-10-07_16-35-16\behavior
04:35:16 PM:INFO:Foraging:Foraging.py:_GetSaveFolder:line 2764:Created new folder: C:\behavior_data\447-2-A\747890\behavior_747890_2024-10-07_16-35-16\behavior\raw.harp
04:35:16 PM:INFO:Foraging:Foraging.py:_GetSaveFolder:line 2767:Created new folder: C:\behavior_data\447-2-A\747890\behavior_747890_2024-10-07_16-35-16\behavior-videos
04:35:16 PM:INFO:Foraging:Foraging.py:_GetSaveFolder:line 2770:Created new folder: C:\behavior_data\447-2-A\747890\behavior_747890_2024-10-07_16-35-16\fib
04:35:16 PM:INFO:rigcontrol:rigcontrol.py:msg_handler:line 56:['/loggerstarted', 'C:\\behavior_data\\447-2-A\\747890\\behavior_747890_2024-10-07_16-35-16\\behavior\\raw.harp', '127.0.0.1', 4002]
04:35:16 PM:ERROR:Foraging:Foraging.py:exception_hook:line 4746:FATAL ERROR: 
Traceback (most recent call last):
  File "C:\Users\svc_aind_behavior\Documents\GitHub\dynamic-foraging-task\src\foraging_gui\Foraging.py", line 4021, in _Start
    GeneratedTrials=GenerateTrials(self)
                    ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\svc_aind_behavior\Documents\GitHub\dynamic-foraging-task\src\foraging_gui\MyFunctions.py", line 105, in __init__
    self._GetTrainingParameters(self.win)
  File "C:\Users\svc_aind_behavior\Documents\GitHub\dynamic-foraging-task\src\foraging_gui\MyFunctions.py", line 1800, in _GetTrainingParameters
    self.TP_auto_train_curriculum_name = _curr.curriculum_name
                                         ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'curriculum_name'
```

**Comment by ellahiltonvano** [comment]
> month old, no re-occurrence
