### ISSUE TITLE
FATAL:xml.etree.ElementTree.ParseError: mismatched tag: line 5172, column 2

### ISSUE THREAD

**Issue by alexpiet** [AllenNeuralDynamics/dynamic-foraging-task#767]
This issue was automatically generated from GUI logs.<br><br>file: Foraging.py<br>function: exception_hook<br>line 4746<br>logfile: W10DT713883/W10DT713883-A_gui_log_2024-10-07_10-09-14.txt<br>boxes: ephys3<br>count: 1<br>text: FATAL:xml.etree.ElementTree.ParseError: mismatched tag: line 5172, column 2<br><br><br>Log context<br>

```
10:09:14 AM:WARNING:Foraging:Foraging.py:_GetSettings:line 1151:Missing setting (save_each_trial), using default: True
10:09:14 AM:WARNING:Foraging:Foraging.py:_GetSettings:line 1151:Missing setting (AutomaticUpload), using default: True
10:09:14 AM:WARNING:Foraging:Foraging.py:_GetSettings:line 1151:Missing setting (manifest_flag_dir), using default: C:\Users\svc_aind_ephys\Documents\aind_watchdog_service\manifest
10:09:14 AM:INFO:Foraging:Foraging.py:_LoadSchedule:line 1040:Loaded behavior schedule
10:09:14 AM:INFO:Foraging:Foraging.py:_GetWaterCalibration:line 1004:Loaded Water Calibration
10:09:14 AM:INFO:Foraging:Foraging.py:_LoadRigJson:line 1529:Skipping rig metadata creation because create_rig_metadata=False
10:09:14 AM:ERROR:Foraging:Foraging.py:exception_hook:line 4746:FATAL ERROR: 
Traceback (most recent call last):
  File "C:\Users\svc_aind_ephys\Documents\GitHub\dynamic-foraging-task\src\foraging_gui\Foraging.py", line 4796, in <module>
    win = Window(box_number=box_number,start_bonsai_ide=start_bonsai_ide)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\svc_aind_ephys\Documents\GitHub\dynamic-foraging-task\src\foraging_gui\Foraging.py", line 95, in __init__
    self._LoadUI()
  File "C:\Users\svc_aind_ephys\Documents\GitHub\dynamic-foraging-task\src\foraging_gui\Foraging.py", line 215, in _LoadUI
    uic.loadUi(self.default_ui, self)
  File "C:\Users\svc_aind_ephys\Anaconda3\envs\Foraging\Lib\site-packages\PyQt5\uic\__init__.py", line 241, in loadUi
    return DynamicUILoader(package).loadUi(uifile, baseinstance, resource_suffix)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\svc_aind_ephys\Anaconda3\envs\Foraging\Lib\site-packages\PyQt5\uic\Loader\loader.py", line 66, in loadUi
    return self.parse(filename, resource_suffix)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\svc_aind_ephys\Anaconda3\envs\Foraging\Lib\site-packages\PyQt5\uic\uiparser.py", line 1020, in parse
    document = parse(filename)
               ^^^^^^^^^^^^^^^
  File "C:\Users\svc_aind_ephys\Anaconda3\envs\Foraging\Lib\xml\etree\ElementTree.py", line 1219, in parse
    tree.parse(source, parser)
  File "C:\Users\svc_aind_ephys\Anaconda3\envs\Foraging\Lib\xml\etree\ElementTree.py", line 581, in parse
    self._root = parser._parse_whole(source)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
xml.etree.ElementTree.ParseError: mismatched tag: line 5172, column 2
```

**Comment by ellahiltonvano** [comment]
> month old, no re occurrence.
