### ISSUE TITLE
TypeError: object of type 'NoneType' has no len()

### ISSUE THREAD

**Issue by alexpiet** [AllenNeuralDynamics/dynamic-foraging-task#774]
This issue was automatically generated from GUI logs.<br><br>file: Foraging.py<br>function: _Move<br>line 753<br>logfile: W10DT714028/W10DT714028-A_gui_log_2024-10-09_10-03-13.txt<br>boxes: 3A<br>count: 1<br>text: TypeError: object of type 'NoneType' has no len()<br><br><br>Log context<br>

```
10:26:56 AM:INFO:GenerateMetadata:GenerateMetadata.py:_get_ophys_stream:line 628:No photometry data stream detected!
10:26:56 AM:INFO:GenerateMetadata:GenerateMetadata.py:_get_high_speed_camera_stream:line 606:No camera data stream detected!
10:26:56 AM:INFO:GenerateMetadata:GenerateMetadata.py:__init__:line 118:Session metadata generated successfully: True
10:26:56 AM:INFO:GenerateMetadata:GenerateMetadata.py:__init__:line 119:Rig metadata generated successfully: True
10:26:56 AM:INFO:GenerateMetadata:GenerateMetadata.py:__init__:line 120:Data description generated successfully: True
10:26:58 AM:INFO:rigcontrol:rigcontrol.py:msg_handler:line 56:['/DelayStartTime', 2594817.6, '127.0.0.1', 4002]
10:26:58 AM:INFO:rigcontrol:rigcontrol.py:msg_handler:line 56:['/BehaviorEvent', 2594817.601504, '127.0.0.1', 4002]
10:26:59 AM:INFO:rigcontrol:rigcontrol.py:msg_handler:line 56:['/GoCueTime', 2594818.582976, '127.0.0.1', 4002]
10:26:59 AM:INFO:rigcontrol:rigcontrol.py:msg_handler:line 56:['/BehaviorEvent', 2594818.58448, '127.0.0.1', 4002]
10:26:59 AM:INFO:rigcontrol:rigcontrol.py:msg_handler:line 56:['/GoCueTimeSoundCard', 2594818.585248, 4, '127.0.0.1']
10:26:59 AM:INFO:rigcontrol:rigcontrol.py:msg_handler:line 56:['/LeftLickTime', 2594818.765856, '127.0.0.1', 4003]
10:26:59 AM:INFO:rigcontrol:rigcontrol.py:msg_handler:line 56:['/RewardOutcomeTime', 2594818.764992, '127.0.0.1', 4002]
10:26:59 AM:INFO:rigcontrol:rigcontrol.py:msg_handler:line 56:['/LeftRewardDeliveryTime', 2594818.764992, '127.0.0.1', 4003]
10:26:59 AM:INFO:rigcontrol:rigcontrol.py:msg_handler:line 56:['/RewardOutcome', 'RewardLeft', '127.0.0.1', 4002]
10:26:59 AM:INFO:rigcontrol:rigcontrol.py:msg_handler:line 56:['/EarnedLeftWaterStartTime', 2594818.764992, '127.0.0.1', 4003]
10:26:59 AM:INFO:rigcontrol:rigcontrol.py:msg_handler:line 56:['/LeftRewardDeliveryTimeHarp', 2594818.767488, '127.0.0.1', 4003]
10:26:59 AM:INFO:rigcontrol:rigcontrol.py:msg_handler:line 56:['/LeftLickTime', 2594818.895488, '127.0.0.1', 4003]
10:27:00 AM:INFO:rigcontrol:rigcontrol.py:msg_handler:line 56:['/LeftLickTime', 2594819.079008, '127.0.0.1', 4003]
10:27:00 AM:INFO:rigcontrol:rigcontrol.py:msg_handler:line 56:['/LeftLickTime', 2594819.213664, '127.0.0.1', 4003]
10:27:00 AM:INFO:rigcontrol:rigcontrol.py:msg_handler:line 56:['/LeftLickTime', 2594819.375392, '127.0.0.1', 4003]
10:27:00 AM:INFO:Foraging:Foraging.py:_CheckStageConnection:line 701:Checking stage connection
10:27:00 AM:INFO:Foraging:Foraging.py:_Move:line 739:Moving stage
10:27:00 AM:INFO:rigcontrol:rigcontrol.py:msg_handler:line 56:['/LeftLickTime', 2594819.54656, '127.0.0.1', 4003]
10:27:00 AM:ERROR:Foraging:Foraging.py:_Move:line 753:Traceback (most recent call last):
  File "C:\Users\svc_aind_behavior\Documents\GitHub\dynamic-foraging-task\src\foraging_gui\Foraging.py", line 751, in _Move
    self._UpdatePosition(current_position,relative_postition)
  File "C:\Users\svc_aind_behavior\Documents\GitHub\dynamic-foraging-task\src\foraging_gui\Foraging.py", line 794, in _UpdatePosition
    for i in range(len(current_position)):
                   ^^^^^^^^^^^^^^^^^^^^^
TypeError: object of type 'NoneType' has no len()
```

**Comment by ellahiltonvano** [comment]
> month old, only happened once
