### ISSUE TITLE
UnboundLocalError: cannot access local variable 'last_positions' where it is not associated with a value

### ISSUE THREAD

**Issue by alexpiet** [AllenNeuralDynamics/dynamic-foraging-task#788]
This issue was automatically generated from GUI logs.<br><br>file: Foraging.py<br>function: _Open<br>line 3152<br>logfile: W10DT713883/W10DT713883-A_gui_log_2024-10-16_14-56-51.txt<br>boxes: ephys3<br>count: 1<br>text: UnboundLocalError: cannot access local variable 'last_positions' where it is not associated with a value<br><br><br>Log context<br>

```
02:57:42 PM:INFO:Foraging:Foraging.py:keyPressEvent:line 1933:Changing parameter: Unrewarded, 200.0 -> 10.0
02:57:42 PM:INFO:Foraging:Foraging.py:keyPressEvent:line 1933:Changing parameter: Ignored, 100.0 -> 10.0
02:57:42 PM:INFO:Foraging:Foraging.py:keyPressEvent:line 1933:Changing parameter: StopIgnores, 20.0 -> 25.0
02:57:42 PM:INFO:Foraging:Foraging.py:keyPressEvent:line 1933:Changing parameter: RightValue, 0.057 -> 0.037
02:57:42 PM:INFO:Foraging:Foraging.py:keyPressEvent:line 1933:Changing parameter: LeftValue, 0.053 -> 0.035
02:57:42 PM:INFO:Foraging:Foraging.py:keyPressEvent:line 1933:Changing parameter: MaxTime, 120.0 -> 90.0
02:57:42 PM:INFO:Foraging:Foraging.py:keyPressEvent:line 1933:Changing parameter: RightValue_volume, 3.0 -> 2.0
02:57:42 PM:INFO:Foraging:Foraging.py:keyPressEvent:line 1933:Changing parameter: LeftValue_volume, 3.0 -> 2.0
02:57:42 PM:INFO:Foraging:Foraging.py:keyPressEvent:line 1933:Changing parameter: BlockMax, 60.0 -> 35.0
02:57:42 PM:INFO:Foraging:Foraging.py:keyPressEvent:line 1933:Changing parameter: DelayBeta, 1.0 -> 0.0
02:57:42 PM:INFO:Foraging:Foraging.py:keyPressEvent:line 1933:Changing parameter: DelayMin, 0.0 -> 1.0
02:57:42 PM:INFO:Foraging:Foraging.py:keyPressEvent:line 1933:Changing parameter: ITIBeta, 2.0 -> 3.0
02:57:42 PM:INFO:Foraging:Foraging.py:keyPressEvent:line 1933:Changing parameter: ITIMax, 8.0 -> 30.0
02:57:42 PM:INFO:Foraging:Foraging.py:keyPressEvent:line 1933:Changing parameter: Multiplier, 0.8 -> 0.5
02:57:42 PM:INFO:Foraging:Foraging.py:keyPressEvent:line 1933:Changing parameter: Unrewarded, 200.0 -> 10.0
02:57:42 PM:INFO:Foraging:Foraging.py:keyPressEvent:line 1933:Changing parameter: Ignored, 100.0 -> 10.0
02:57:42 PM:INFO:Foraging:Foraging.py:keyPressEvent:line 1933:Changing parameter: StopIgnores, 20.0 -> 25.0
02:57:42 PM:INFO:Foraging:Foraging.py:keyPressEvent:line 1933:Changing parameter: RightValue, 0.057 -> 0.037
02:57:42 PM:INFO:Foraging:Foraging.py:keyPressEvent:line 1933:Changing parameter: LeftValue, 0.053 -> 0.035
02:57:42 PM:INFO:Foraging:Foraging.py:keyPressEvent:line 1933:Changing parameter: MaxTime, 120.0 -> 90.0
02:57:42 PM:INFO:Foraging:Foraging.py:keyPressEvent:line 1933:Changing parameter: RightValue_volume, 3.0 -> 2.0
02:57:42 PM:INFO:Foraging:Foraging.py:keyPressEvent:line 1933:Changing parameter: LeftValue_volume, 3.0 -> 2.0
02:57:42 PM:WARNING:warnings:warnings.py:_showwarnmsg:line 110:C:\Users\svc_aind_ephys\Documents\GitHub\dynamic-foraging-task\src\foraging_gui\Visualization.py:170: RuntimeWarning: Mean of empty slice
  RewardedHistoryF[i+1-kernel_size]=np.nanmean(RewardedHistoryT[i+1-kernel_size:i+1])

02:57:43 PM:ERROR:Foraging:Foraging.py:_Open:line 3152:Traceback (most recent call last):
  File "C:\Users\svc_aind_ephys\Documents\GitHub\dynamic-foraging-task\src\foraging_gui\Foraging.py", line 3149, in _Open
    self.current_stage.move_absolute_3d(float(last_positions[0]),float(last_positions[1]),float(last_positions[2]))
                                              ^^^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'last_positions' where it is not associated with a value
```

**Comment by ellahiltonvano** [comment]
> month old, only happened once

**Comment by alexpiet** [comment]
This issue reoccurred:<br><br>file: Foraging.py<br>function: _Open<br>line 3131<br>logfile: W10DT714086/W10DT714086-D_gui_log_2024-12-04_14-20-47.txt<br>boxes: 1D<br>count: 1<br>text: UnboundLocalError: cannot access local variable 'last_positions' where it is not associated with a value<br><details><summary> GUI Log snippet (click for full log)

```
09:54:48 AM:INFO:Foraging:Foraging.py:keyPressEvent:line 1922:Changing parameter: RightValue_volume, 3.0 -> 2.0
09:54:48 AM:INFO:Foraging:Foraging.py:keyPressEvent:line 1922:Changing parameter: RightValue, 0.034 -> 0.024
09:54:48 AM:INFO:Foraging:Foraging.py:keyPressEvent:line 1922:Changing parameter: Unrewarded, 200.0 -> 7.0
09:54:48 AM:INFO:Foraging:Foraging.py:keyPressEvent:line 1922:Changing parameter: warm_min_trial, 60.0 -> 50.0
09:54:48 AM:INFO:Foraging:Foraging.py:keyPressEvent:line 1922:Changing parameter: GiveWaterR, 0.034 -> 0.024
09:54:48 AM:INFO:Foraging:Foraging.py:keyPressEvent:line 1922:Changing parameter: GiveWaterR_volume, 3.0 -> 2.0
09:54:48 AM:INFO:Foraging:Foraging.py:keyPressEvent:line 1922:Changing parameter: PositionZ, 3840.5 -> 2641.0
09:54:48 AM:INFO:Foraging:Foraging.py:keyPressEvent:line 1922:Changing parameter: PositionY, 7374.0 -> 6574.0
09:54:48 AM:INFO:Foraging:Foraging.py:keyPressEvent:line 1922:Changing parameter: PositionX, 9097.5 -> 9697.5
09:54:48 AM:INFO:Foraging:Foraging.py:keyPressEvent:line 1922:Changing parameter: SuggestedWater,  -> 0.298
09:54:48 AM:INFO:Foraging:Foraging.py:keyPressEvent:line 1922:Changing parameter: BaseWeight,  -> 24.88
09:54:48 AM:INFO:Foraging:Foraging.py:keyPressEvent:line 1922:Changing parameter: TargetWeight,  -> 21.148
09:54:48 AM:WARNING:warnings:warnings.py:_showwarnmsg:line 110:C:\Users\svc_aind_behavior\Documents\GitHub\dynamic-foraging-task\src\foraging_gui\Visualization.py:160: RuntimeWarning: Mean of empty slice
  RewardedHistoryF[i+1-self.kernel_size]=np.nanmean(RewardedHistoryT[i+1-self.kernel_size:i+1])

09:54:49 AM:ERROR:Foraging:Foraging.py:_Open:line 3131:Traceback (most recent call last):
  File "C:\Users\svc_aind_behavior\Documents\GitHub\dynamic-foraging-task\src\foraging_gui\Foraging.py", line 3128, in _Open
    self.current_stage.move_absolute_3d(float(last_positions[0]),float(last_positions[1]),float(last_positions[2]))
                                              ^^^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'last_positions' where it is not associated with a value
```
</summary>
Full GUI log 

```
02:20:47 PM:INFO:Foraging:Foraging.py:start_gui_log_file:line 4661:Starting logfile!
02:20:47 PM:INFO:Foraging:Foraging.py:log_git_hash:line 4672:Python version: 3.11.9 | packaged by Anaconda, Inc. | (main, Apr 19 2024, 16:40:41) [MSC v.1916 64 bit (AMD64)]
02:20:47 PM:INFO:Foraging:Foraging.py:log_git_hash:line 4689:Current git commit branch, hash: main, 1a7c9d3d1aa10284caed44ba9b223c6bfbb8ff5f
02:20:47 PM:INFO:Foraging:Foraging.py:log_git_hash:line 4693:Current foraging_gui version: 1.6.10
02:20:47 PM:WARNING:Foraging:Foraging.py:log_git_hash:line 4703:local repository is clean
02:20:47 PM:INFO:Foraging:Foraging.py:<module>:line 4804:Setting QApplication attributes
02:20:47 PM:INFO:Foraging:Foraging.py:<module>:line 4812:Starting QApplication and Window
02:20:47 PM:INFO:Foraging:Foraging.py:__init__:line 69:Creating Window
02:20:47 PM:INFO:Foraging:Foraging.py:_GetSettings:line 1174:Loaded settings_box file
02:20:47 PM:INFO:Foraging:Foraging.py:_GetSettings:line 1202:Loaded settings file
02:20:47 PM:WARNING:Foraging:Foraging.py:_GetSettings:line 1212:Missing setting (temporary_video_folder), using default: C:\Users\svc_aind_behavior\Documents\temporaryvideo
02:20:47 PM:WARNING:Foraging:Foraging.py:_GetSettings:line 1212:Missing setting (FIP_settings), using default: C:\Users\svc_aind_behavior\Documents\FIPSettings
02:20:47 PM:WARNING:Foraging:Foraging.py:_GetSettings:line 1212:Missing setting (bonsai_config_path), using default: C:\Users\svc_aind_behavior\Documents\GitHub\dynamic-foraging-task\bonsai\Bonsai.config
02:20:47 PM:WARNING:Foraging:Foraging.py:_GetSettings:line 1212:Missing setting (open_ephys_machine_ip_address), using default: 
02:20:47 PM:WARNING:Foraging:Foraging.py:_GetSettings:line 1212:Missing setting (metadata_dialog_folder), using default: C:\Users\svc_aind_behavior\Documents\ForagingSettings\metadata_dialog\
02:20:47 PM:WARNING:Foraging:Foraging.py:_GetSettings:line 1212:Missing setting (rig_metadata_folder), using default: C:\Users\svc_aind_behavior\Documents\ForagingSettings\rig_metadata\
02:20:47 PM:WARNING:Foraging:Foraging.py:_GetSettings:line 1212:Missing setting (project_info_file), using default: C:\Users\svc_aind_behavior\Documents\ForagingSettings\Project Name and Funding Source v2.csv
02:20:47 PM:WARNING:Foraging:Foraging.py:_GetSettings:line 1212:Missing setting (schedule_path), using default: Z:\dynamic_foraging\DynamicForagingSchedule.csv
02:20:47 PM:WARNING:Foraging:Foraging.py:_GetSettings:line 1212:Missing setting (lick_spout_distance_box1), using default: 5000
02:20:47 PM:WARNING:Foraging:Foraging.py:_GetSettings:line 1212:Missing setting (lick_spout_distance_box2), using default: 5000
02:20:47 PM:WARNING:Foraging:Foraging.py:_GetSettings:line 1212:Missing setting (lick_spout_distance_box3), using default: 5000
02:20:47 PM:WARNING:Foraging:Foraging.py:_GetSettings:line 1212:Missing setting (lick_spout_distance_box4), using default: 5000
02:20:47 PM:WARNING:Foraging:Foraging.py:_GetSettings:line 1212:Missing setting (name_mapper_file), using default: C:\Users\svc_aind_behavior\Documents\ForagingSettings\name_mapper.json
02:20:47 PM:WARNING:Foraging:Foraging.py:_GetSettings:line 1212:Missing setting (save_each_trial), using default: True
02:20:47 PM:WARNING:Foraging:Foraging.py:_GetSettings:line 1212:Missing setting (AutomaticUpload), using default: True
02:20:47 PM:WARNING:Foraging:Foraging.py:_GetSettings:line 1212:Missing setting (manifest_flag_dir), using default: C:\Users\svc_aind_behavior\Documents\aind_watchdog_service\manifest
02:20:47 PM:WARNING:Foraging:Foraging.py:_GetSettings:line 1212:Missing setting (auto_engage), using default: True
02:20:47 PM:WARNING:Foraging:Foraging.py:_GetSettings:line 1212:Missing setting (clear_figure_after_save), using default: True
02:20:47 PM:WARNING:Foraging:Foraging.py:_GetSettings:line 1212:Missing setting (add_default_project_name), using default: True
02:20:47 PM:INFO:Foraging:Foraging.py:_LoadSchedule:line 1100:Loaded behavior schedule
02:20:47 PM:INFO:Foraging:Foraging.py:_GetWaterCalibration:line 1064:Loaded Water Calibration
02:20:47 PM:INFO:Foraging:Foraging.py:_load_most_recent_rig_json:line 1534:Found existing rig.json: rig_447-1-D_2024-12-03_10_00_29.json
02:20:47 PM:INFO:RigJsonBuilder:RigJsonBuilder.py:build_rig_json_core:line 60:building rig json
02:20:47 PM:INFO:RigJsonBuilder:RigJsonBuilder.py:build_rig_json_core:line 624:finished building rig json
02:20:47 PM:INFO:RigJsonBuilder:RigJsonBuilder.py:build_rig_json:line 53:Using existing rig json
02:20:47 PM:INFO:Foraging:Foraging.py:_LoadUI:line 275:Using ForagingGUI.ui interface
02:20:47 PM:INFO:Foraging:Foraging.py:__init__:line 119:Setting Window title: 447-1-D
02:20:47 PM:INFO:Foraging:Foraging.py:_InitializeBonsai:line 1371:Trying to connect to already running Bonsai
02:20:47 PM:INFO:Foraging:Foraging.py:_ConnectOSC:line 1418:connecting to GUI and Bonsai through OSC
02:20:48 PM:INFO:Foraging:Foraging.py:_InitializeBonsai:line 1375:Could not connect: timed out
02:20:48 PM:INFO:Foraging:Foraging.py:_InitializeBonsai:line 1384:Starting Bonsai
02:20:48 PM:INFO:Foraging:Foraging.py:log_subprocess_output:line 4776:BONSAI logging starting
02:20:49 PM:INFO:Foraging:Foraging.py:_ConnectOSC:line 1418:connecting to GUI and Bonsai through OSC
02:20:50 PM:INFO:Foraging:Foraging.py:_InitializeBonsai:line 1398:Could not connect, total waiting time 0.5 seconds: timed out
02:20:50 PM:INFO:Foraging:Foraging.py:_ConnectOSC:line 1418:connecting to GUI and Bonsai through OSC
02:20:51 PM:INFO:Foraging:Foraging.py:_InitializeBonsai:line 1398:Could not connect, total waiting time 1.0 seconds: timed out
02:20:52 PM:INFO:Foraging:Foraging.py:_ConnectOSC:line 1418:connecting to GUI and Bonsai through OSC
02:20:52 PM:INFO:Foraging:Foraging.py:_InitializeBonsai:line 1401:Connected to Bonsai after 1.5 seconds
02:20:52 PM:INFO:Foraging:Foraging.py:_InitializeBonsai:line 1402:Bonsai started successfully
02:20:52 PM:INFO:Foraging:Foraging.py:_ConnectSlims:line 1281:Attempting to connect to Slims
02:20:52 PM:INFO:rigcontrol:rigcontrol.py:msg_handler:line 52:['/PhotometryFalling', 28423066.40352, '127.0.0.1', 4033], displaying at 0.5 Hz
02:20:52 PM:INFO:rigcontrol:rigcontrol.py:msg_handler:line 56:['/BehaviorEvent', 28423066.411488, '127.0.0.1', 4032]
02:20:53 PM:INFO:Foraging:Foraging.py:_ConnectSlims:line 1298:Successfully connected to Slims
02:20:53 PM:WARNING:Dialogs:Dialogs.py:_LoadCalibrationParameters:line 480:could not find water calibration parameters: C:\Users\svc_aind_behavior\Documents\ForagingSettings\WaterCalibrationPar_4.json
02:20:53 PM:INFO:Foraging:Foraging.py:keyPressEvent:line 1863:processing parameter changes
02:20:54 PM:INFO:Foraging:Foraging.py:_InitializeMotorStage:line 875:Scanning for newscale stages
02:20:54 PM:INFO:Foraging:Foraging.py:_InitializeMotorStage:line 890:found 2 newscale stages
02:20:54 PM:INFO:Foraging:Foraging.py:_InitializeMotorStage:line 914:Found the newscale stage from the settings file
02:20:54 PM:INFO:Foraging:Foraging.py:_connect_stage:line 941:Successfully connected to newscale stage: 46098
02:20:54 PM:INFO:Foraging:Foraging.py:_CheckStageConnection:line 761:Checking stage connection
02:20:54 PM:INFO:Foraging:Foraging.py:_GetPositions:line 773:Grabbing current stage position
02:20:54 PM:INFO:Foraging:Foraging.py:_StopPhotometry:line 3428:Checking that photometry is not running
02:20:54 PM:INFO:Foraging:Foraging.py:_StopPhotometry:line 3438:Photometry excitation stopped
02:20:54 PM:INFO:Foraging:Foraging.py:_load_most_recent_rig_json:line 1534:Found existing rig.json: rig_447-1-D_2024-12-03_10_00_29.json
02:20:54 PM:INFO:Foraging:Foraging.py:_ReconnectBonsai:line 971:attempting to close bonsai connection
02:20:56 PM:INFO:Foraging:Foraging.py:_ReconnectBonsai:line 979:bonsai connection closed
02:20:56 PM:INFO:Foraging:Foraging.py:_ReconnectBonsai:line 981:attempting to restart bonsai
02:20:56 PM:INFO:Foraging:Foraging.py:_InitializeBonsai:line 1371:Trying to connect to already running Bonsai
02:20:56 PM:INFO:Foraging:Foraging.py:_ConnectOSC:line 1418:connecting to GUI and Bonsai through OSC
02:20:56 PM:INFO:Foraging:Foraging.py:_InitializeBonsai:line 1378:Connected to already running Bonsai
02:20:56 PM:INFO:Foraging:Foraging.py:_InitializeBonsai:line 1379:Bonsai started successfully
02:20:56 PM:INFO:Foraging:Foraging.py:__init__:line 219:Start up complete
02:20:57 PM:INFO:aws_util:aws_util.py:import_df_from_s3:line 115:Dataframe imported from s3://aind-behavior-data/foraging_nwb_bonsai_processed/df_sessions.pkl, len(df) = 5833
02:20:58 PM:INFO:aws_util:aws_util.py:import_df_from_s3:line 115:Dataframe imported from s3://aind-behavior-data/foraging_auto_training/df_manager_447_demo.pkl, len(df) = 4352
02:20:58 PM:INFO:aws_util:aws_util.py:download_dir_from_s3:line 140:134 objects downloaded from s3://aind-behavior-data/foraging_auto_training/saved_curriculums/ to C:\Users\svc_aind_behavior/capsule/scratch/saved_curriculums/
02:20:58 PM:INFO:curriculum_manager:curriculum_manager.py:download_curriculums:line 162:Found 29 curriculums in C:\Users\svc_aind_behavior/capsule/scratch/saved_curriculums/
02:20:59 PM:INFO:aws_util:aws_util.py:download_dir_from_s3:line 140:134 objects downloaded from s3://aind-behavior-data/foraging_auto_training/saved_curriculums/ to C:\Users\svc_aind_behavior/.aind_auto_train/curriculum_manager/
02:20:59 PM:INFO:curriculum_manager:curriculum_manager.py:download_curriculums:line 162:Found 29 curriculums in C:\Users\svc_aind_behavior/.aind_auto_train/curriculum_manager/
02:20:59 PM:INFO:Dialogs:Dialogs.py:update_auto_train_fields:line 2273:No entry found in df_training_manager for subject_id: 0
02:20:59 PM:INFO:Dialogs:Dialogs.py:_override_curriculum_clicked:line 2621:Override stage clicked: state=2
02:20:59 PM:INFO:Dialogs:Dialogs.py:_update_stage_to_apply:line 2647:Current stage to apply: unknown training stage @unknown curriculum
02:22:52 PM:INFO:Foraging:Foraging.py:_StartBleaching:line 3386:Start bleaching!
09:54:04 AM:INFO:Foraging:Foraging.py:_StopCurrentSession:line 3581:Stopping current trials
09:54:13 AM:INFO:Foraging:Foraging.py:_Open:line 2930:Quick load failed, user hit cancel or X
09:54:34 AM:INFO:Foraging:Foraging.py:_StopCurrentSession:line 3581:Stopping current trials
09:54:47 AM:INFO:Foraging:Foraging.py:_Open:line 2948:Quick load success: C:\behavior_data\447-1-D\754895\behavior_754895_2024-12-04_10-22-17\behavior\754895_2024-12-04_10-22-17.json
09:54:47 AM:INFO:Foraging:Foraging.py:_NewSession:line 3491:New Session pressed
09:54:47 AM:INFO:Foraging:Foraging.py:_NewSession:line 3523:Resetting session run flag
09:54:47 AM:INFO:Foraging:Foraging.py:_StopPhotometry:line 3428:Checking that photometry is not running
09:54:47 AM:INFO:Foraging:Foraging.py:_StopPhotometry:line 3438:Photometry excitation stopped
09:54:47 AM:INFO:Foraging:Foraging.py:_NewSession:line 3561:New Session complete
09:54:47 AM:INFO:Foraging:Foraging.py:keyPressEvent:line 1863:processing parameter changes
09:54:47 AM:INFO:Foraging:Foraging.py:keyPressEvent:line 1922:Changing parameter: DelayMin, 0.0 -> 0.25
09:54:47 AM:INFO:Foraging:Foraging.py:keyPressEvent:line 1922:Changing parameter: DelayBeta, 1.0 -> 0.0
09:54:47 AM:INFO:Foraging:Foraging.py:keyPressEvent:line 1922:Changing parameter: DelayMax, 1.0 -> 0.25
09:54:47 AM:INFO:Foraging:Foraging.py:keyPressEvent:line 1922:Changing parameter: RightValue, 0.03 -> 0.034
09:54:47 AM:INFO:Foraging:Foraging.py:keyPressEvent:line 1922:Changing parameter: LeftValue, 0.03 -> 0.025
09:54:47 AM:INFO:Foraging:Foraging.py:keyPressEvent:line 1922:Changing parameter: LeftValue_volume, 3.0 -> 2.0
09:54:47 AM:INFO:Foraging:Foraging.py:keyPressEvent:line 1922:Changing parameter: ID, 0.0 -> 754895.0
09:54:47 AM:INFO:Foraging:Foraging.py:keyPressEvent:line 1922:Changing parameter: DelayMin, 0.0 -> 0.25
09:54:47 AM:INFO:Foraging:Foraging.py:keyPressEvent:line 1922:Changing parameter: DelayBeta, 1.0 -> 0.0
09:54:47 AM:INFO:Foraging:Foraging.py:keyPressEvent:line 1922:Changing parameter: DelayMax, 1.0 -> 0.25
09:54:47 AM:INFO:Foraging:Foraging.py:keyPressEvent:line 1922:Changing parameter: RightValue, 0.03 -> 0.034
09:54:47 AM:INFO:Foraging:Foraging.py:keyPressEvent:line 1922:Changing parameter: LeftValue, 0.03 -> 0.025
09:54:47 AM:INFO:Foraging:Foraging.py:keyPressEvent:line 1922:Changing parameter: LeftValue_volume, 3.0 -> 2.0
09:54:47 AM:INFO:Foraging:Foraging.py:keyPressEvent:line 1922:Changing parameter: GiveWaterL, 0.03 -> 0.025
09:54:47 AM:INFO:Foraging:Foraging.py:keyPressEvent:line 1922:Changing parameter: GiveWaterR, 0.03 -> 0.034
09:54:47 AM:INFO:Foraging:Foraging.py:keyPressEvent:line 1922:Changing parameter: GiveWaterL_volume, 3.0 -> 2.0
09:54:47 AM:INFO:Foraging:Foraging.py:keyPressEvent:line 1922:Changing parameter: PositionZ,  -> 3840.5
09:54:47 AM:INFO:Foraging:Foraging.py:keyPressEvent:line 1922:Changing parameter: PositionY,  -> 7374.0
09:54:47 AM:INFO:Foraging:Foraging.py:keyPressEvent:line 1922:Changing parameter: PositionX,  -> 9097.5
09:54:48 AM:INFO:Foraging:Foraging.py:keyPressEvent:line 1863:processing parameter changes
09:54:48 AM:INFO:Foraging:Foraging.py:keyPressEvent:line 1863:processing parameter changes
09:54:48 AM:INFO:Foraging:Foraging.py:keyPressEvent:line 1922:Changing parameter: BlockMax, 60.0 -> 35.0
09:54:48 AM:INFO:Foraging:Foraging.py:keyPressEvent:line 1922:Changing parameter: RewardDelay, 0.0 -> 0.1
09:54:48 AM:INFO:Foraging:Foraging.py:keyPressEvent:line 1922:Changing parameter: ITIMax, 8.0 -> 10.0
09:54:48 AM:INFO:Foraging:Foraging.py:keyPressEvent:line 1922:Changing parameter: ITIBeta, 2.0 -> 3.0
09:54:48 AM:INFO:Foraging:Foraging.py:keyPressEvent:line 1922:Changing parameter: ResponseTime, 1.0 -> 1.5
09:54:48 AM:INFO:Foraging:Foraging.py:keyPressEvent:line 1922:Changing parameter: BlockMax, 60.0 -> 35.0
09:54:48 AM:INFO:Foraging:Foraging.py:keyPressEvent:line 1922:Changing parameter: RewardDelay, 0.0 -> 0.1
09:54:48 AM:INFO:Foraging:Foraging.py:keyPressEvent:line 1922:Changing parameter: ITIMax, 8.0 -> 10.0
09:54:48 AM:INFO:Foraging:Foraging.py:keyPressEvent:line 1922:Changing parameter: ITIBeta, 2.0 -> 3.0
09:54:48 AM:INFO:Foraging:Foraging.py:keyPressEvent:line 1922:Changing parameter: ResponseTime, 1.0 -> 1.5
09:54:48 AM:INFO:Foraging:Foraging.py:keyPressEvent:line 1863:processing parameter changes
09:54:48 AM:INFO:Foraging:Foraging.py:keyPressEvent:line 1863:processing parameter changes
09:54:48 AM:INFO:Foraging:Foraging.py:_QComboBoxUpdate:line 1832:Field updated: FIPMode:Axon
09:54:48 AM:INFO:Foraging:Foraging.py:keyPressEvent:line 1863:processing parameter changes
09:54:48 AM:INFO:Foraging:Foraging.py:keyPressEvent:line 1922:Changing parameter: Ignored, 100.0 -> 7.0
09:54:48 AM:INFO:Foraging:Foraging.py:keyPressEvent:line 1922:Changing parameter: BlockBeta, 20.0 -> 10.0
09:54:48 AM:INFO:Foraging:Foraging.py:keyPressEvent:line 1922:Changing parameter: StopIgnores, 20.0 -> 25.0
09:54:48 AM:INFO:Foraging:Foraging.py:keyPressEvent:line 1922:Changing parameter: MaxTime, 120.0 -> 75.0
09:54:48 AM:INFO:Foraging:Foraging.py:keyPressEvent:line 1922:Changing parameter: RewardConsumeTime, 3.0 -> 1.0
09:54:48 AM:INFO:Foraging:Foraging.py:keyPressEvent:line 1922:Changing parameter: Multiplier, 0.8 -> 0.5
09:54:48 AM:INFO:Foraging:Foraging.py:keyPressEvent:line 1922:Changing parameter: RightValue_volume, 3.0 -> 2.0
09:54:48 AM:INFO:Foraging:Foraging.py:keyPressEvent:line 1922:Changing parameter: RightValue, 0.034 -> 0.024
09:54:48 AM:INFO:Foraging:Foraging.py:keyPressEvent:line 1922:Changing parameter: Unrewarded, 200.0 -> 7.0
09:54:48 AM:INFO:Foraging:Foraging.py:keyPressEvent:line 1922:Changing parameter: warm_min_trial, 60.0 -> 50.0
09:54:48 AM:INFO:Foraging:Foraging.py:keyPressEvent:line 1922:Changing parameter: Ignored, 100.0 -> 7.0
09:54:48 AM:INFO:Foraging:Foraging.py:keyPressEvent:line 1922:Changing parameter: BlockBeta, 20.0 -> 10.0
09:54:48 AM:INFO:Foraging:Foraging.py:keyPressEvent:line 1922:Changing parameter: StopIgnores, 20.0 -> 25.0
09:54:48 AM:INFO:Foraging:Foraging.py:keyPressEvent:line 1922:Changing parameter: MaxTime, 120.0 -> 75.0
09:54:48 AM:INFO:Foraging:Foraging.py:keyPressEvent:line 1922:Changing parameter: RewardConsumeTime, 3.0 -> 1.0
09:54:48 AM:INFO:Foraging:Foraging.py:keyPressEvent:line 1922:Changing parameter: Multiplier, 0.8 -> 0.5
09:54:48 AM:INFO:Foraging:Foraging.py:keyPressEvent:line 1922:Changing parameter: RightValue_volume, 3.0 -> 2.0
09:54:48 AM:INFO:Foraging:Foraging.py:keyPressEvent:line 1922:Changing parameter: RightValue, 0.034 -> 0.024
09:54:48 AM:INFO:Foraging:Foraging.py:keyPressEvent:line 1922:Changing parameter: Unrewarded, 200.0 -> 7.0
09:54:48 AM:INFO:Foraging:Foraging.py:keyPressEvent:line 1922:Changing parameter: warm_min_trial, 60.0 -> 50.0
09:54:48 AM:INFO:Foraging:Foraging.py:keyPressEvent:line 1922:Changing parameter: GiveWaterR, 0.034 -> 0.024
09:54:48 AM:INFO:Foraging:Foraging.py:keyPressEvent:line 1922:Changing parameter: GiveWaterR_volume, 3.0 -> 2.0
09:54:48 AM:INFO:Foraging:Foraging.py:keyPressEvent:line 1922:Changing parameter: PositionZ, 3840.5 -> 2641.0
09:54:48 AM:INFO:Foraging:Foraging.py:keyPressEvent:line 1922:Changing parameter: PositionY, 7374.0 -> 6574.0
09:54:48 AM:INFO:Foraging:Foraging.py:keyPressEvent:line 1922:Changing parameter: PositionX, 9097.5 -> 9697.5
09:54:48 AM:INFO:Foraging:Foraging.py:keyPressEvent:line 1922:Changing parameter: SuggestedWater,  -> 0.298
09:54:48 AM:INFO:Foraging:Foraging.py:keyPressEvent:line 1922:Changing parameter: BaseWeight,  -> 24.88
09:54:48 AM:INFO:Foraging:Foraging.py:keyPressEvent:line 1922:Changing parameter: TargetWeight,  -> 21.148
09:54:48 AM:WARNING:warnings:warnings.py:_showwarnmsg:line 110:C:\Users\svc_aind_behavior\Documents\GitHub\dynamic-foraging-task\src\foraging_gui\Visualization.py:160: RuntimeWarning: Mean of empty slice
  RewardedHistoryF[i+1-self.kernel_size]=np.nanmean(RewardedHistoryT[i+1-self.kernel_size:i+1])

09:54:49 AM:ERROR:Foraging:Foraging.py:_Open:line 3131:Traceback (most recent call last):
  File "C:\Users\svc_aind_behavior\Documents\GitHub\dynamic-foraging-task\src\foraging_gui\Foraging.py", line 3128, in _Open
    self.current_stage.move_absolute_3d(float(last_positions[0]),float(last_positions[1]),float(last_positions[2]))
                                              ^^^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'last_positions' where it is not associated with a value
```
</details>
