### ISSUE TITLE
FATAL:FileNotFoundError: [WinError 3] The system cannot find the path specified: 'D:\\BehaviorData\\323_EPHYS3\\741211\\behavior_741211_2024-10-10_12-05-56\\behavior-videos'

### ISSUE THREAD

**Issue by alexpiet** [AllenNeuralDynamics/dynamic-foraging-task#791]
This issue was automatically generated from GUI logs.<br><br>file: Foraging.py<br>function: exception_hook<br>line 4746<br>logfile: W10DT713883/W10DT713883-A_gui_log_2024-10-17_17-41-15.txt<br>boxes: ephys3<br>count: 2<br>text: FATAL:FileNotFoundError: [WinError 3] The system cannot find the path specified: 'D:\\BehaviorData\\323_EPHYS3\\741211\\behavior_741211_2024-10-10_12-05-56\\behavior-videos'<br><br><br>Log context<br>

```
05:44:19 PM:INFO:Foraging:Foraging.py:keyPressEvent:line 1933:Changing parameter: Ignored, 100.0 -> 10.0
05:44:19 PM:INFO:Foraging:Foraging.py:keyPressEvent:line 1933:Changing parameter: StopIgnores, 20.0 -> 25.0
05:44:19 PM:INFO:Foraging:Foraging.py:keyPressEvent:line 1933:Changing parameter: RightValue, 0.057 -> 0.037
05:44:19 PM:INFO:Foraging:Foraging.py:keyPressEvent:line 1933:Changing parameter: LeftValue, 0.053 -> 0.035
05:44:19 PM:INFO:Foraging:Foraging.py:keyPressEvent:line 1933:Changing parameter: MaxTime, 120.0 -> 75.0
05:44:19 PM:INFO:Foraging:Foraging.py:keyPressEvent:line 1933:Changing parameter: RightValue_volume, 3.0 -> 2.0
05:44:19 PM:INFO:Foraging:Foraging.py:keyPressEvent:line 1933:Changing parameter: LeftValue_volume, 3.0 -> 2.0
05:44:20 PM:INFO:Foraging:Foraging.py:keyPressEvent:line 1874:processing parameter changes
05:44:20 PM:INFO:Foraging:Foraging.py:keyPressEvent:line 1933:Changing parameter: ID, 0.0 -> 741211.0
05:44:20 PM:INFO:Foraging:Foraging.py:keyPressEvent:line 1933:Changing parameter: BaseWeight,  -> 32.5
05:44:20 PM:INFO:Foraging:Foraging.py:keyPressEvent:line 1933:Changing parameter: TargetWeight,  -> 27.625
05:44:20 PM:INFO:Foraging:Foraging.py:keyPressEvent:line 1933:Changing parameter: PositionY, 9902.0 -> 10113.0
05:44:20 PM:INFO:Foraging:Foraging.py:keyPressEvent:line 1933:Changing parameter: PositionX, 4984.0 -> 4717.5
05:44:20 PM:INFO:Foraging:Foraging.py:keyPressEvent:line 1933:Changing parameter: PositionZ, 9324.5 -> 9912.5
05:44:20 PM:INFO:Foraging:Foraging.py:keyPressEvent:line 1874:processing parameter changes
05:44:20 PM:INFO:Foraging:Foraging.py:keyPressEvent:line 1874:processing parameter changes
05:44:20 PM:INFO:Foraging:Foraging.py:keyPressEvent:line 1874:processing parameter changes
05:44:20 PM:INFO:Foraging:Foraging.py:keyPressEvent:line 1874:processing parameter changes
05:44:20 PM:INFO:Foraging:Foraging.py:keyPressEvent:line 1874:processing parameter changes
05:44:21 PM:INFO:Foraging:Foraging.py:keyPressEvent:line 1874:processing parameter changes
05:44:21 PM:INFO:Foraging:Foraging.py:keyPressEvent:line 1874:processing parameter changes
05:44:21 PM:INFO:Foraging:Foraging.py:keyPressEvent:line 1874:processing parameter changes
05:44:21 PM:ERROR:Foraging:Foraging.py:exception_hook:line 4746:FATAL ERROR: 
Traceback (most recent call last):
  File "C:\Users\svc_aind_ephys\Documents\GitHub\dynamic-foraging-task\src\foraging_gui\Foraging.py", line 3173, in _Open
    self._check_drop_frames(save_tag=0)
  File "C:\Users\svc_aind_ephys\Documents\GitHub\dynamic-foraging-task\src\foraging_gui\Foraging.py", line 581, in _check_drop_frames
    elif len(os.listdir(video_folder)) == 0:
             ^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'D:\\BehaviorData\\323_EPHYS3\\741211\\behavior_741211_2024-10-10_12-05-56\\behavior-videos'
```

**Comment by ellahiltonvano** [comment]
> month old, only happened once
