### ISSUE TITLE
FATAL:json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by alexpiet** [AllenNeuralDynamics/dynamic-foraging-task#839]
This issue was automatically generated from GUI logs.<br><br>file: Foraging.py<br>function: exception_hook<br>line 4770<br>logfile: W10DT714084/W10DT714084-A_gui_log_2024-10-23_13-32-05.txt<br>boxes: 2A<br>count: 1<br>text: FATAL:json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)<br><br><br>Log context<br>

```
01:32:19 PM:INFO:Dialogs:Dialogs.py:_update_stage_to_apply:line 2771:Current stage to apply: unknown training stage @unknown curriculum
01:32:19 PM:ERROR:Foraging:Foraging.py:exception_hook:line 4770:FATAL ERROR: 
Traceback (most recent call last):
  File "C:\Users\svc_aind_behavior\Documents\GitHub\dynamic-foraging-task\src\foraging_gui\Foraging.py", line 4831, in <module>
    win.create_auto_train_dialog()
  File "C:\Users\svc_aind_behavior\Documents\GitHub\dynamic-foraging-task\src\foraging_gui\Foraging.py", line 4537, in create_auto_train_dialog
    self.AutoTrain_dialog = AutoTrainDialog(MainWindow=self, parent=None)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\svc_aind_behavior\Documents\GitHub\dynamic-foraging-task\src\foraging_gui\Dialogs.py", line 2349, in __init__
    self.update_auto_train_fields(subject_id=self.MainWindow.ID.text())
  File "C:\Users\svc_aind_behavior\Documents\GitHub\dynamic-foraging-task\src\foraging_gui\Dialogs.py", line 2520, in update_auto_train_fields
    self._show_available_curriculums()
  File "C:\Users\svc_aind_behavior\Documents\GitHub\dynamic-foraging-task\src\foraging_gui\Dialogs.py", line 2649, in _show_available_curriculums
    self.df_curriculums = self.curriculum_manager.df_curriculums()
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\svc_aind_behavior\AppData\Local\miniconda3\envs\Foraging\Lib\site-packages\aind_auto_train\curriculum_manager.py", line 76, in df_curriculums
    curriculum_description=json.load(
                           ^^^^^^^^^^
  File "C:\Users\svc_aind_behavior\AppData\Local\miniconda3\envs\Foraging\Lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "C:\Users\svc_aind_behavior\AppData\Local\miniconda3\envs\Foraging\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\svc_aind_behavior\AppData\Local\miniconda3\envs\Foraging\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\svc_aind_behavior\AppData\Local\miniconda3\envs\Foraging\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by alexpiet** [comment]
This issue reoccurred:<br><br>file: Foraging.py<br>function: exception_hook<br>line 4770<br>logfile: W10DT714084/W10DT714084-A_gui_log_2024-10-23_13-32-05.txt<br>boxes: 2A<br>count: 1<br>text: FATAL:json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)<br><br><br>Log context<br>

```
01:32:19 PM:INFO:Dialogs:Dialogs.py:_update_stage_to_apply:line 2771:Current stage to apply: unknown training stage @unknown curriculum
01:32:19 PM:ERROR:Foraging:Foraging.py:exception_hook:line 4770:FATAL ERROR: 
Traceback (most recent call last):
  File "C:\Users\svc_aind_behavior\Documents\GitHub\dynamic-foraging-task\src\foraging_gui\Foraging.py", line 4831, in <module>
    win.create_auto_train_dialog()
  File "C:\Users\svc_aind_behavior\Documents\GitHub\dynamic-foraging-task\src\foraging_gui\Foraging.py", line 4537, in create_auto_train_dialog
    self.AutoTrain_dialog = AutoTrainDialog(MainWindow=self, parent=None)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\svc_aind_behavior\Documents\GitHub\dynamic-foraging-task\src\foraging_gui\Dialogs.py", line 2349, in __init__
    self.update_auto_train_fields(subject_id=self.MainWindow.ID.text())
  File "C:\Users\svc_aind_behavior\Documents\GitHub\dynamic-foraging-task\src\foraging_gui\Dialogs.py", line 2520, in update_auto_train_fields
    self._show_available_curriculums()
  File "C:\Users\svc_aind_behavior\Documents\GitHub\dynamic-foraging-task\src\foraging_gui\Dialogs.py", line 2649, in _show_available_curriculums
    self.df_curriculums = self.curriculum_manager.df_curriculums()
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\svc_aind_behavior\AppData\Local\miniconda3\envs\Foraging\Lib\site-packages\aind_auto_train\curriculum_manager.py", line 76, in df_curriculums
    curriculum_description=json.load(
                           ^^^^^^^^^^
  File "C:\Users\svc_aind_behavior\AppData\Local\miniconda3\envs\Foraging\Lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "C:\Users\svc_aind_behavior\AppData\Local\miniconda3\envs\Foraging\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\svc_aind_behavior\AppData\Local\miniconda3\envs\Foraging\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\svc_aind_behavior\AppData\Local\miniconda3\envs\Foraging\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by alexpiet** [comment]
What mouse and what curriculum is causing this problem?

**Comment by ellahiltonvano** [comment]
729674, PM RA (Jaimie)

**Comment by ellahiltonvano** [comment]
> month old
