### ISSUE TITLE
FATAL:AttributeError: 'GenerateTrials' object has no attribute 'TP_RunLength'

### ISSUE THREAD

**Issue by alexpiet** [AllenNeuralDynamics/dynamic-foraging-task#857]
This issue was automatically generated from GUI logs.<br><br>file: Foraging.py<br>function: exception_hook<br>line 4819<br>logfile: W10DT714674/W10DT714674-D_gui_log_2024-10-28_09-34-45.txt<br>boxes: 6D<br>count: 3<br>text: FATAL:AttributeError: 'GenerateTrials' object has no attribute 'TP_RunLength'<br><br><br>Log context<br>

```
09:49:28 AM:INFO:rigcontrol:rigcontrol.py:msg_handler:line 56:['/BehaviorEvent', 9334427.433504, '127.0.0.1', 4032]
09:49:28 AM:INFO:rigcontrol:rigcontrol.py:msg_handler:line 56:['/GoCueTime', 9334427.464992, '127.0.0.1', 4032]
09:49:28 AM:INFO:rigcontrol:rigcontrol.py:msg_handler:line 56:['/GoCueTimeSoundCard', 9334427.467168, 4, '127.0.0.1']
09:49:28 AM:INFO:rigcontrol:rigcontrol.py:msg_handler:line 56:['/AutoRightWaterStartTime', 9334427.466976, '127.0.0.1', 4033]
09:49:28 AM:INFO:rigcontrol:rigcontrol.py:msg_handler:line 56:['/BehaviorEvent', 9334427.467488, '127.0.0.1', 4032]
09:49:28 AM:INFO:rigcontrol:rigcontrol.py:msg_handler:line 56:['/RightRewardDeliveryTimeHarp', 9334427.46848, '127.0.0.1', 4033]
09:49:30 AM:INFO:rigcontrol:rigcontrol.py:msg_handler:line 56:['/RightLickTime', 9334430.139552, '127.0.0.1', 4033]
09:49:30 AM:INFO:rigcontrol:rigcontrol.py:msg_handler:line 56:['/RewardOutcomeTime', 9334430.138976, '127.0.0.1', 4032]
09:49:30 AM:INFO:rigcontrol:rigcontrol.py:msg_handler:line 56:['/RewardOutcome', 'ErrorRight', '127.0.0.1', 4032]
09:49:30 AM:INFO:rigcontrol:rigcontrol.py:msg_handler:line 56:['/RightLickTime', 9334430.241856, '127.0.0.1', 4033]
09:49:30 AM:INFO:rigcontrol:rigcontrol.py:msg_handler:line 56:['/RightLickTime', 9334430.33344, '127.0.0.1', 4033]
09:49:31 AM:INFO:rigcontrol:rigcontrol.py:msg_handler:line 56:['/RightLickTime', 9334430.445568, '127.0.0.1', 4033]
09:49:31 AM:INFO:rigcontrol:rigcontrol.py:msg_handler:line 56:['/RightLickTime', 9334430.59136, '127.0.0.1', 4033]
09:49:31 AM:INFO:rigcontrol:rigcontrol.py:msg_handler:line 56:['/RightLickTime', 9334430.7024, '127.0.0.1', 4033]
09:49:31 AM:INFO:rigcontrol:rigcontrol.py:msg_handler:line 56:['/RightLickTime', 9334430.820416, '127.0.0.1', 4033]
09:49:31 AM:INFO:rigcontrol:rigcontrol.py:msg_handler:line 56:['/RightLickTime', 9334430.968384, '127.0.0.1', 4033]
09:49:31 AM:INFO:rigcontrol:rigcontrol.py:msg_handler:line 56:['/TrialEndTime', 9334431.132, '127.0.0.1', 4032]
09:49:31 AM:INFO:rigcontrol:rigcontrol.py:msg_handler:line 56:['/BehaviorEvent', 9334431.133504, '127.0.0.1', 4032]
09:49:31 AM:ERROR:Foraging:Foraging.py:exception_hook:line 4819:FATAL ERROR: 
Traceback (most recent call last):
  File "C:\Users\svc_aind_behavior\Documents\GitHub\dynamic-foraging-task\src\foraging_gui\Foraging.py", line 3672, in _thread_complete
    self.GeneratedTrials._GenerateATrial(self.Channel4)
  File "C:\Users\svc_aind_behavior\Documents\GitHub\dynamic-foraging-task\src\foraging_gui\MyFunctions.py", line 125, in _GenerateATrial
    self._check_coupled_block_transition()
  File "C:\Users\svc_aind_behavior\Documents\GitHub\dynamic-foraging-task\src\foraging_gui\MyFunctions.py", line 416, in _check_coupled_block_transition
    self._check_advanced_block_switch()
  File "C:\Users\svc_aind_behavior\Documents\GitHub\dynamic-foraging-task\src\foraging_gui\MyFunctions.py", line 476, in _check_advanced_block_switch
    kernel_size=int(self.TP_RunLength)
                    ^^^^^^^^^^^^^^^^^
AttributeError: 'GenerateTrials' object has no attribute 'TP_RunLength'
```

**Comment by alexpiet** [comment]
This feels like a bug, maybe a missing parameter in autotrain?

**Comment by alexpiet** [comment]
@micahwoodard I think this is caused by this weeks updates, because we moved a parameter from the main window to the visualization plot: `self.RunLength=win.RunLength.text` (Visualization.py, line 18)

I dont know what RunLength does, and if its a parameter, or just for plotting. It might also explain why the "finish_frac" isn't plotting all the way. Because I bet we are now changing "RunLength" to 2, and so the finish_frac is not defined sometimes

**Comment by alexpiet** [comment]
Yup, MyFunctions.py, line 569 uses RunLength to compute the choice fraction, and MyFunctions.py line 476 is what caused the crash

**Comment by ellahiltonvano** [comment]
Since the finish_frac display issue has been resolved I'll close this one as well. @alexpiet feel free to reopen if this is an independent issue.
