### ISSUE TITLE
FATAL:KeyError: 'SLIMS_USERNAME'

### ISSUE THREAD

**Issue by alexpiet** [AllenNeuralDynamics/dynamic-foraging-task#858]
This issue was automatically generated from GUI logs.<br><br>file: Foraging.py<br>function: exception_hook<br>line 4770<br>logfile: DT300178/DT300178-A_gui_log_2024-10-28_12-35-49.txt<br>boxes: 9D<br>count: 5<br>text: FATAL:KeyError: 'SLIMS_USERNAME'<br><br><br>Log context<br>

```
12:35:49 PM:INFO:Foraging:Foraging.py:_LoadSchedule:line 1044:Loaded behavior schedule
12:35:49 PM:WARNING:Foraging:Foraging.py:_GetWaterCalibration:line 1012:Did not find a recent water calibration file
12:35:49 PM:INFO:Foraging:Foraging.py:_load_most_recent_rig_json:line 1524:Found existing rig.json: rig_428-9-D_2024-10-28_11_36_22.json
12:35:49 PM:INFO:RigJsonBuilder:RigJsonBuilder.py:build_rig_json_core:line 60:building rig json
12:35:49 PM:INFO:RigJsonBuilder:RigJsonBuilder.py:build_rig_json_core:line 624:finished building rig json
12:35:49 PM:INFO:RigJsonBuilder:RigJsonBuilder.py:build_rig_json:line 53:Using existing rig json
12:35:49 PM:INFO:Foraging:Foraging.py:_LoadUI:line 221:Using ForagingGUI.ui interface
12:35:49 PM:INFO:Foraging:Foraging.py:__init__:line 102:Setting Window title: 428-9-D
12:35:49 PM:INFO:Foraging:Foraging.py:_InitializeBonsai:line 1352:Trying to connect to already running Bonsai
12:35:49 PM:INFO:Foraging:Foraging.py:_ConnectOSC:line 1405:connecting to GUI and Bonsai through OSC
12:35:50 PM:INFO:Foraging:Foraging.py:_InitializeBonsai:line 1356:Could not connect: timed out
12:35:50 PM:INFO:Foraging:Foraging.py:_InitializeBonsai:line 1367:Starting Bonsai
12:35:50 PM:INFO:Foraging:Foraging.py:log_subprocess_output:line 4777:BONSAI logging starting
12:35:51 PM:INFO:Foraging:Foraging.py:_ConnectOSC:line 1405:connecting to GUI and Bonsai through OSC
12:35:52 PM:INFO:Foraging:Foraging.py:_InitializeBonsai:line 1381:Could not connect, total waiting time 0.5 seconds: timed out
12:35:52 PM:INFO:Foraging:Foraging.py:_ConnectOSC:line 1405:connecting to GUI and Bonsai through OSC
12:35:53 PM:INFO:Foraging:Foraging.py:_InitializeBonsai:line 1381:Could not connect, total waiting time 1.0 seconds: timed out
12:35:54 PM:INFO:Foraging:Foraging.py:_ConnectOSC:line 1405:connecting to GUI and Bonsai through OSC
12:35:55 PM:INFO:Foraging:Foraging.py:_InitializeBonsai:line 1381:Could not connect, total waiting time 1.5 seconds: timed out
12:35:55 PM:INFO:Foraging:Foraging.py:_ConnectOSC:line 1405:connecting to GUI and Bonsai through OSC
12:35:56 PM:INFO:Foraging:Foraging.py:_InitializeBonsai:line 1384:Connected to Bonsai after 2.0 seconds
12:35:56 PM:INFO:Foraging:Foraging.py:_InitializeBonsai:line 1385:Bonsai started successfully
12:35:56 PM:INFO:Foraging:Foraging.py:_ConnectSlims:line 1223:Attempting to connect to Slims
12:35:56 PM:ERROR:Foraging:Foraging.py:exception_hook:line 4770:FATAL ERROR: 
Traceback (most recent call last):
  File "c:\Users\svc_aind_behavior\Documents\GitHub\dynamic-foraging-task\src\foraging_gui\Foraging.py", line 1224, in _ConnectSlims
    self.slims_client = SlimsClient(username=os.environ['SLIMS_USERNAME'],
                                             ~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "<frozen os>", line 679, in __getitem__
KeyError: 'SLIMS_USERNAME'
```

**Comment by ellahiltonvano** [comment]
This is a result of SLIMS_USERNAME not being set correctly on the rig. Not a bug, user error.
