### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'subject_id'

### ISSUE THREAD

**Issue by alexpiet** [AllenNeuralDynamics/dynamic-foraging-task#887]
This issue was automatically generated from GUI logs.<br><br>file: Foraging.py<br>function: _Save<br>line 2734<br>logfile: W10DT714670/W10DT714670-A_gui_log_2024-11-01_08-44-12.txt<br>boxes: ephys4<br>count: 1<br>text: AttributeError: 'NoneType' object has no attribute 'subject_id'<br><br><br>Log context<br>

```
10:23:45 AM:INFO:rigcontrol:rigcontrol.py:msg_handler:line 56:['/LeftLickTime', 1280128.412768, '127.0.0.1', 4003]
10:23:46 AM:INFO:rigcontrol:rigcontrol.py:msg_handler:line 56:['/LeftLickTime', 1280128.720896, '127.0.0.1', 4003]
10:24:18 AM:INFO:rigcontrol:rigcontrol.py:msg_handler:line 56:['/RightLickTime', 1280160.76352, '127.0.0.1', 4003]
10:24:18 AM:INFO:rigcontrol:rigcontrol.py:msg_handler:line 56:['/LeftLickTime', 1280160.809568, '127.0.0.1', 4003]
10:24:19 AM:INFO:rigcontrol:rigcontrol.py:msg_handler:line 56:['/LeftLickTime', 1280162.160096, '127.0.0.1', 4003]
10:24:19 AM:INFO:rigcontrol:rigcontrol.py:msg_handler:line 56:['/RightLickTime', 1280162.186688, '127.0.0.1', 4003]
10:24:20 AM:INFO:rigcontrol:rigcontrol.py:msg_handler:line 56:['/LeftLickTime', 1280162.658656, '127.0.0.1', 4003]
10:26:01 AM:INFO:Foraging:Foraging.py:_Save:line 2491:Saving current session, ForceSave=True
10:26:01 AM:INFO:Foraging:Foraging.py:_GetWaterCalibration:line 1046:Loaded Water Calibration
10:26:01 AM:INFO:Foraging:Foraging.py:_NewSession:line 3577:New Session pressed
10:26:06 AM:INFO:Foraging:Foraging.py:_NewSession:line 3651:New Session complete
10:26:06 AM:INFO:Foraging:Foraging.py:end_session_log:line 4206:Closing log file at D:\dynamic-foraging\322_EPHYS4\729674\behavior_729674_2024-11-01_08-53-00\behavior\python_gui_log.txt
10:26:06 AM:INFO:Foraging:Foraging.py:log_subprocess_output:line 4867:BONSAI: 
10:26:06 AM:INFO:Foraging:Foraging.py:log_subprocess_output:line 4867:BONSAI: 
10:26:06 AM:INFO:Foraging:Foraging.py:log_subprocess_output:line 4867:BONSAI: 
10:26:06 AM:INFO:Foraging:Foraging.py:log_subprocess_output:line 4867:BONSAI: 
10:26:06 AM:INFO:Foraging:Foraging.py:log_subprocess_output:line 4867:BONSAI: 
10:26:06 AM:INFO:Foraging:Foraging.py:log_subprocess_output:line 4867:BONSAI: 
10:26:06 AM:INFO:Foraging:Foraging.py:log_subprocess_output:line 4867:BONSAI: 
10:26:06 AM:INFO:Foraging:Foraging.py:log_subprocess_output:line 4867:BONSAI: 
10:26:13 AM:INFO:GenerateMetadata:GenerateMetadata.py:__init__:line 90:processing:D:\dynamic-foraging\322_EPHYS4\729674\behavior_729674_2024-11-01_08-53-00
10:26:13 AM:INFO:GenerateMetadata:GenerateMetadata.py:_handle_edge_cases:line 398:Cannot log reward delivery in session metadata - missing fields
10:26:13 AM:INFO:GenerateMetadata:GenerateMetadata.py:_handle_edge_cases:line 442:Missing rig metadata for session metadata
10:26:13 AM:INFO:GenerateMetadata:GenerateMetadata.py:_session:line 537:rig metadata is empty!
10:26:13 AM:ERROR:Foraging:Foraging.py:_Save:line 2733:Error generating session metadata: 'NoneType' object has no attribute 'subject_id'
10:26:13 AM:ERROR:Foraging:Foraging.py:_Save:line 2734:Traceback (most recent call last):
  File "C:\Users\svc_aind_ephys\Documents\GitHub\dynamic-foraging-task\src\foraging_gui\Foraging.py", line 1291, in _AddWaterLogResult
    logging.info(f'Attempting to fetch mouse {session.subject_id} from Slims')
                                              ^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'subject_id'
```

**Comment by alexpiet** [comment]
This issue reoccurred:<br><br>file: Foraging.py<br>function: _Save<br>line 2734<br>logfile: W10DT714670/W10DT714670-A_gui_log_2024-11-04_08-47-54.txt<br>boxes: ephys4<br>count: 1<br>text: AttributeError: 'NoneType' object has no attribute 'subject_id'<br><br><br>Log context<br>

```
10:20:59 AM:INFO:rigcontrol:rigcontrol.py:msg_handler:line 56:['/BehaviorEvent', 1542761.711488, '127.0.0.1', 4002]
10:21:00 AM:INFO:rigcontrol:rigcontrol.py:msg_handler:line 56:['/RewardOutcomeTime', 1542762.708992, '127.0.0.1', 4002]
10:21:00 AM:INFO:rigcontrol:rigcontrol.py:msg_handler:line 56:['/RewardOutcome', 'NoResponse', '127.0.0.1', 4002]
10:21:03 AM:INFO:rigcontrol:rigcontrol.py:msg_handler:line 56:['/TrialEndTime', 1542765.725984, '127.0.0.1', 4002]
10:21:03 AM:INFO:rigcontrol:rigcontrol.py:msg_handler:line 56:['/BehaviorEvent', 1542765.727488, '127.0.0.1', 4002]
10:21:58 AM:INFO:rigcontrol:rigcontrol.py:msg_handler:line 56:['/LeftLickTime', 1542820.26608, '127.0.0.1', 4003]
10:21:58 AM:INFO:rigcontrol:rigcontrol.py:msg_handler:line 56:['/RightLickTime', 1542820.291104, '127.0.0.1', 4003]
10:24:04 AM:INFO:Foraging:Foraging.py:_Save:line 2491:Saving current session, ForceSave=True
10:24:04 AM:INFO:Foraging:Foraging.py:_GetWaterCalibration:line 1046:Loaded Water Calibration
10:24:04 AM:INFO:Foraging:Foraging.py:_NewSession:line 3577:New Session pressed
10:24:09 AM:INFO:Foraging:Foraging.py:_NewSession:line 3651:New Session complete
10:24:09 AM:INFO:Foraging:Foraging.py:end_session_log:line 4206:Closing log file at D:\dynamic-foraging\322_EPHYS4\729674\behavior_729674_2024-11-04_08-55-33\behavior\python_gui_log.txt
10:24:09 AM:INFO:Foraging:Foraging.py:log_subprocess_output:line 4867:BONSAI: 
10:24:09 AM:INFO:Foraging:Foraging.py:log_subprocess_output:line 4867:BONSAI: 
10:24:10 AM:INFO:Foraging:Foraging.py:log_subprocess_output:line 4867:BONSAI: 
10:24:10 AM:INFO:Foraging:Foraging.py:log_subprocess_output:line 4867:BONSAI: 
10:24:10 AM:INFO:Foraging:Foraging.py:log_subprocess_output:line 4867:BONSAI: 
10:24:10 AM:INFO:Foraging:Foraging.py:log_subprocess_output:line 4867:BONSAI: 
10:24:10 AM:INFO:Foraging:Foraging.py:log_subprocess_output:line 4867:BONSAI: 
10:24:10 AM:INFO:Foraging:Foraging.py:log_subprocess_output:line 4867:BONSAI: 
10:24:16 AM:INFO:GenerateMetadata:GenerateMetadata.py:__init__:line 90:processing:D:\dynamic-foraging\322_EPHYS4\729674\behavior_729674_2024-11-04_08-55-33
10:24:16 AM:INFO:GenerateMetadata:GenerateMetadata.py:_handle_edge_cases:line 398:Cannot log reward delivery in session metadata - missing fields
10:24:16 AM:INFO:GenerateMetadata:GenerateMetadata.py:_handle_edge_cases:line 442:Missing rig metadata for session metadata
10:24:16 AM:INFO:GenerateMetadata:GenerateMetadata.py:_session:line 537:rig metadata is empty!
10:24:16 AM:ERROR:Foraging:Foraging.py:_Save:line 2733:Error generating session metadata: 'NoneType' object has no attribute 'subject_id'
10:24:16 AM:ERROR:Foraging:Foraging.py:_Save:line 2734:Traceback (most recent call last):
  File "C:\Users\svc_aind_ephys\Documents\GitHub\dynamic-foraging-task\src\foraging_gui\Foraging.py", line 1291, in _AddWaterLogResult
    logging.info(f'Attempting to fetch mouse {session.subject_id} from Slims')
                                              ^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'subject_id'
```

**Comment by ellahiltonvano** [comment]
The rig metadata isn't being generated on the new ephys rig, this should be addressed asap

**Comment by ellahiltonvano** [comment]
has not reoccurred.
