### ISSUE TITLE
RuntimeError: Device at address 01 is not present on this interface.

### ISSUE THREAD

**Issue by alexpiet** [AllenNeuralDynamics/dynamic-foraging-task#943]
This issue was automatically generated from GUI logs.<br><br>file: Foraging.py<br>function: _connect_stage<br>line 919<br>logfile: W10DT713669/W10DT713669-A_gui_log_2024-11-04_15-31-38.txt<br>boxes: ephys1<br>count: 3<br>text: RuntimeError: Device at address 01 is not present on this interface.<br><br><br>Log context<br>

```
03:31:45 PM:INFO:Foraging:Foraging.py:_ConnectSlims:line 1263:Attempting to connect to Slims
03:31:45 PM:INFO:Foraging:Foraging.py:_ConnectSlims:line 1280:Successfully connected to Slims
03:31:45 PM:WARNING:Dialogs:Dialogs.py:_LoadCalibrationParameters:line 509:could not find water calibration parameters: C:\Users\svc_aind_ephys\Documents\ForagingSettings\WaterCalibrationPar_1.json
03:31:46 PM:INFO:Foraging:Foraging.py:keyPressEvent:line 1919:processing parameter changes
03:31:46 PM:INFO:Foraging:Foraging.py:_InitializeMotorStage:line 857:Scanning for newscale stages
03:31:46 PM:INFO:Foraging:Foraging.py:_InitializeMotorStage:line 871:found 2 newscale stages
03:31:46 PM:INFO:Foraging:Foraging.py:_InitializeMotorStage:line 895:Found the newscale stage from the settings file
03:31:46 PM:ERROR:Foraging:Foraging.py:_connect_stage:line 919:Traceback (most recent call last):
  File "C:\Users\svc_aind_ephys\Documents\GitHub\dynamic-foraging-task\src\foraging_gui\Foraging.py", line 917, in _connect_stage
    self.current_stage=Stage(serial=instance)
                       ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\svc_aind_ephys\Documents\GitHub\dynamic-foraging-task\src\foraging_gui\stage.py", line 80, in __init__
    self.device = USBXYZStage(usb_interface=USBInterface(serial))
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\svc_aind_ephys\.conda\envs\Foraging\Lib\site-packages\newscale\multistage.py", line 400, in __init__
    stages = {'x': M3LinearSmartStage(self.interface, '01'),
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\svc_aind_ephys\.conda\envs\Foraging\Lib\site-packages\newscale\stage.py", line 51, in __init__
    self.get_firmware_version()  # Necessary to handshake with the PC.
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\svc_aind_ephys\.conda\envs\Foraging\Lib\site-packages\newscale\stage.py", line 105, in get_firmware_version
    return self._send(self._get_cmd_str(Cmd.FIRMWARE_VERSION))[-1]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\svc_aind_ephys\.conda\envs\Foraging\Lib\site-packages\newscale\stage.py", line 92, in _send
    self.interface.send(cmd_str, address=self.address)
  File "C:\Users\svc_aind_ephys\.conda\envs\Foraging\Lib\site-packages\newscale\interfaces.py", line 179, in send
    self._select_stage(address)
  File "C:\Users\svc_aind_ephys\.conda\envs\Foraging\Lib\site-packages\newscale\interfaces.py", line 48, in _select_stage
    raise RuntimeError(f"Device at address {address} is not "
RuntimeError: Device at address 01 is not present on this interface.
```

**Comment by ellahiltonvano** [comment]
newscale stage issue.
